In [1]:
import tensorflow as tf
sess = tf.InteractiveSession()

In [2]:
x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.]])

x = tf.reshape(x, [1, 2, 3, 1])  # give a shape accepted by tf.nn.max_pool

valid_pad = tf.nn.max_pool(x, [1, 2, 2, 1], [1, 1, 1, 1], padding='VALID')
same_pad = tf.nn.max_pool(x, [1, 2, 2, 1], [1, 1, 1, 1], padding='SAME')

print valid_pad.get_shape() == [1, 1, 1, 1]  # valid_pad is [5.]
print same_pad.get_shape() == [1, 1, 2, 1]   # same_pad is  [5., 6.]


print valid_pad.eval()
print valid_pad.eval().shape
print same_pad.eval()
print same_pad.eval().shape

False
False
[[[[ 5.]
   [ 6.]]]]
(1, 1, 2, 1)
[[[[ 5.]
   [ 6.]
   [ 6.]]

  [[ 5.]
   [ 6.]
   [ 6.]]]]
(1, 2, 3, 1)


In [3]:
x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.]])

x = tf.reshape(x, [1, 2, 3, 1])  # give a shape accepted by tf.nn.max_pool

valid_pad = tf.nn.max_pool(x, [1, 2, 2, 1], [1, 2, 2, 1], padding='VALID')
same_pad = tf.nn.max_pool(x, [1, 2, 2, 1], [1, 2, 2, 1], padding='SAME')

print valid_pad.get_shape() == [1, 1, 1, 1]  # valid_pad is [5.]
print same_pad.get_shape() == [1, 1, 2, 1]   # same_pad is  [5., 6.]


print valid_pad.eval()
print valid_pad.eval().shape
print same_pad.eval()
print same_pad.eval().shape

True
True
[[[[ 5.]]]]
(1, 1, 1, 1)
[[[[ 5.]
   [ 6.]]]]
(1, 1, 2, 1)


In [4]:
x = tf.constant([[1., 2., 3., 4.],
                 [4., 5., 6., 7.],
                [8., 9., 10., 11.],
                [12.,13.,14.,15.]])

x = tf.reshape(x, [1, 4, 4, 1])  # give a shape accepted by tf.nn.max_pool

valid_pad = tf.nn.max_pool(x, [1, 2, 2, 1], [1, 2, 2, 1], padding='VALID')
same_pad = tf.nn.max_pool(x, [1, 2, 2, 1], [1, 2, 2, 1], padding='SAME')

print valid_pad.get_shape() # valid_pad is [5.]
print same_pad.get_shape() # same_pad is  [5., 6.]

#ess = tf.InteractiveSession()
#ess.run(tf.initialize_all_variables())
print valid_pad.eval()
print same_pad.eval()

(1, 2, 2, 1)
(1, 2, 2, 1)
[[[[  5.]
   [  7.]]

  [[ 13.]
   [ 15.]]]]
[[[[  5.]
   [  7.]]

  [[ 13.]
   [ 15.]]]]


In [5]:
x = tf.constant([[1., 2., 3., 4.],
                 [4., 5., 6., 7.],
                [8., 9., 10., 11.],
                [12.,13.,14.,15.]])

x = tf.reshape(x, [1, 4, 4, 1])  # give a shape accepted by tf.nn.max_pool

W = tf.constant([[1., 0.],
                [0., 1.]])

W = tf.reshape(W, [2, 2, 1, 1])

valid_pad = tf.nn.conv2d(x, W, strides = [1, 1, 1, 1], padding='VALID')
same_pad = tf.nn.conv2d(x, W, strides = [1, 1, 1, 1],padding='SAME')

print valid_pad.get_shape()   # valid_pad is [5.]
print same_pad.get_shape()   # same_pad is  [5., 6.]

#ess = tf.InteractiveSession()
#ess.run(tf.initialize_all_variables())
print valid_pad.eval()
print same_pad.eval()

(1, 3, 3, 1)
(1, 4, 4, 1)
[[[[  6.]
   [  8.]
   [ 10.]]

  [[ 13.]
   [ 15.]
   [ 17.]]

  [[ 21.]
   [ 23.]
   [ 25.]]]]
[[[[  6.]
   [  8.]
   [ 10.]
   [  4.]]

  [[ 13.]
   [ 15.]
   [ 17.]
   [  7.]]

  [[ 21.]
   [ 23.]
   [ 25.]
   [ 11.]]

  [[ 12.]
   [ 13.]
   [ 14.]
   [ 15.]]]]


In [6]:
x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.]])

x = tf.reshape(x, [1, 2, 3, 1])  # give a shape accepted by tf.nn.max_pool

W = tf.constant([[1., 0.],
                [0., 1.]])

W = tf.reshape(W, [2, 2, 1, 1])

valid_pad = tf.nn.conv2d(x, W, strides = [1, 1, 1, 1], padding='VALID')
same_pad = tf.nn.conv2d(x, W, strides = [1, 1, 1, 1],padding='SAME')

print valid_pad.get_shape()   # valid_pad is [5.]
print same_pad.get_shape()   # same_pad is  [5., 6.]

#ess = tf.InteractiveSession()
#ess.run(tf.initialize_all_variables())
print valid_pad.eval()
print same_pad.eval()

(1, 1, 2, 1)
(1, 2, 3, 1)
[[[[ 6.]
   [ 8.]]]]
[[[[ 6.]
   [ 8.]
   [ 3.]]

  [[ 4.]
   [ 5.]
   [ 6.]]]]


In [7]:
tf.nn.conv2d?

In [9]:
x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.]])

x = tf.reshape(x, [1, 2, 3, 1])  # give a shape accepted by tf.nn.max_pool

W = tf.constant([2.])

W = tf.reshape(W, [1, 1, 1, 1])

valid_pad = tf.nn.conv2d(x, W, strides = [1, 1, 1, 1], padding='VALID')
same_pad = tf.nn.conv2d(x, W, strides = [1, 1, 1, 1],padding='SAME')

print valid_pad.get_shape()   # valid_pad is [5.]
print same_pad.get_shape()   # same_pad is  [5., 6.]

#ess = tf.InteractiveSession()
#ess.run(tf.initialize_all_variables())
print valid_pad.eval()
print same_pad.eval()

(1, 2, 3, 1)
(1, 2, 3, 1)
[[[[  2.]
   [  4.]
   [  6.]]

  [[  8.]
   [ 10.]
   [ 12.]]]]
[[[[  2.]
   [  4.]
   [  6.]]

  [[  8.]
   [ 10.]
   [ 12.]]]]


In [27]:
x = tf.constant([
                 [
                 [1., 2., 3.],
                 [4., 5., 6.]
                 ],
                 [
                 [2. , 2., 2.],
                 [3., 3., 3.]
                 ]
                ])

print x.eval().shape


x = tf.reshape(x, [1, 2, 3, 2])  # give a shape accepted by tf.nn.max_pool

x.eval()

print x[0, : , :, 0].eval()
print x[0, : , :, 1].eval()
print x.eval()


W = tf.constant([2., 3.])

W = tf.reshape(W, [1, 1, 2, 1])

valid_pad = tf.nn.conv2d(x, W, strides = [1, 1, 1, 1], padding='VALID')
same_pad = tf.nn.conv2d(x, W, strides = [1, 1, 1, 1],padding='SAME')

print valid_pad.get_shape()   # valid_pad is [5.]
print same_pad.get_shape()   # same_pad is  [5., 6.]

#ess = tf.InteractiveSession()
#ess.run(tf.initialize_all_variables())
print valid_pad.eval()
print same_pad.eval()

(2, 2, 3)
[[ 1.  3.  5.]
 [ 2.  2.  3.]]
[[ 2.  4.  6.]
 [ 2.  3.  3.]]
[[[[ 1.  2.]
   [ 3.  4.]
   [ 5.  6.]]

  [[ 2.  2.]
   [ 2.  3.]
   [ 3.  3.]]]]
(1, 2, 3, 1)
(1, 2, 3, 1)
[[[[  8.]
   [ 18.]
   [ 28.]]

  [[ 10.]
   [ 13.]
   [ 15.]]]]
[[[[  8.]
   [ 18.]
   [ 28.]]

  [[ 10.]
   [ 13.]
   [ 15.]]]]


In [32]:
tf.pack?

In [34]:
x = tf.constant([1, 2])
y = tf.constant([3, 4])
z = tf.constant([5,6])
tf.pack([x, y, z]).eval()

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

In [36]:
tf.concat(0, [x,y, z]).eval()

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [37]:
tf.pack([3,4]).eval()

array([3, 4], dtype=int32)

In [40]:
from tensorflow.python.util import nest
nest.flatten?

In [42]:
nest.flatten([[1,2,3],[4,5,6]])

[1, 2, 3, 4, 5, 6]

In [43]:
tf.reduce_sum?