In [1]:
import tensorflow as tf
sess = tf.InteractiveSession()

In [3]:
x = tf.constant([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
idx = tf.constant([1, 0, 2])
idx_flattened = tf.range(0, tf.shape(x)[0]) * tf.shape(x)[1] + idx
y = tf.gather(tf.reshape(x, [-1]),  # flatten input
              idx_flattened)  # use flattened indices

y.eval()

array([2, 4, 9], dtype=int32)

In [4]:
x = tf.constant([[1, 2, 3, 0, 0],
                 [4, 5, 6, 7, 0],
                 [7, 8, 0, 0, 0]])
x.eval()

array([[1, 2, 3, 0, 0],
       [4, 5, 6, 7, 0],
       [7, 8, 0, 0, 0]], dtype=int32)

In [6]:
length = tf.reduce_sum(tf.sign(x), 1)
length.eval()

array([3, 4, 2], dtype=int32)

In [7]:
rows = tf.range(x.get_shape()[0])
rows.eval()

array([0, 1, 2], dtype=int32)

In [8]:
tf.pack([rows, length]).eval()

array([[0, 1, 2],
       [3, 4, 2]], dtype=int32)

In [10]:
coords = tf.transpose(tf.pack([rows, length]))
coords.eval()

array([[0, 3],
       [1, 4],
       [2, 2]], dtype=int32)

In [12]:
(tf.sparse_to_dense(coords, x.get_shape(), 1) + x).eval()

array([[1, 2, 3, 1, 0],
       [4, 5, 6, 7, 1],
       [7, 8, 1, 0, 0]], dtype=int32)

In [ ]:
tf.reset_default_graph()
row_indices = tf.constant([1, 1, 2])
col_indices = tf.constant([0, 2, 3])
x = tf.zeros((3, 4))
sess = tf.InteractiveSession()

# get list of ((row1, col1), (row2, col2), ..)
coords = tf.transpose(tf.pack([row_indices, col_indices]))

# get tensor with 1's at positions (row1, col1),...
binary_mask = tf.sparse_to_dense(coords, x.get_shape(), 1)

# convert 1/0 to True/False
binary_mask = tf.cast(binary_mask, tf.bool)

twos = 2*tf.ones(x.get_shape())

# make new x out of old values or 2, depending on mask 
x = tf.select(binary_mask, twos, x)

print x.eval()

In [11]:
tf.select?

In [14]:
tf.constant?

In [15]:
tf.range?

In [16]:
x = tf.constant([[1, 2, 3, 0, 0],
                 [4, 5, 6, 7, 0],
                 [7, 8, 0, 0, 0]], dtype=tf.int64)

In [19]:
length = tf.reduce_sum(tf.sign(x), 1)
length.eval()
length.dtype

tf.int64

In [20]:
tf.sign(x).dtype

tf.int64

In [21]:
tf.sign?

In [23]:
tf.sparse_to_dense?

In [24]:
x.dtype

tf.int64

In [25]:
tf.shape(x).dtype

tf.int32

In [26]:
tf.shape(x)

<tf.Tensor 'Shape_3:0' shape=(2,) dtype=int32>

In [ ]:
tf.ran