In [ ]:
import tensorflow as tf
sess = tf.InteractiveSession()

In [ ]:
x = tf.constant([
        [1., 2., 3.],
        [2., 3., 0.]         
                ])

In [ ]:
x.eval()

In [ ]:
def length(data):
  mask = tf.sign(data)
  return tf.reduce_sum(mask, 1)

In [ ]:
length(x).eval()

In [ ]:
tf.reshape(x, [-1]).eval()

In [ ]:
x[:,:2].eval()

In [ ]:
tf.shape(x)[1].eval()

In [ ]:
x.get_shape()[1]

In [ ]:
(tf.shape(x)[1] - 1).eval()

In [ ]:
x[:,:(tf.shape(x)[1] - 1)].eval()

In [ ]:
tf.gather?

In [ ]:
x = tf.constant([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
idx = tf.constant([1, 0, 2])
idx_flattened = tf.range(0, tf.shape(x)[0]) * tf.shape(x)[1] + idx
y = tf.gather(tf.reshape(x, [-1]),  # flatten input
              idx_flattened)  # use flattened indices

with tf.Session(''):
  print y.eval()  # [2 4 9]

In [ ]:
tf.gather(x, 1).eval()

In [ ]:
tf.gather(x, tf.shape(x)[0] - 1).eval()

In [ ]:
tf.gather(x, [tf.range(0, tf.shape(x)[0] - 1)]).eval()

In [ ]:
tf.__version__

In [ ]:
x[:,:-1]

In [ ]:
tf.gather_nd?

In [ ]:
tf.gather?

In [ ]:
tf.transpose(tf.gather(tf.transpose(x), tf.range(0, tf.shape(x)[1] - 1))).eval()

In [ ]:
from tensorflow.contrib.layers.python.layers import utils

In [ ]:
utils.last_dimension(x.get_shape())

In [ ]:
utils.first_dimension(x.get_shape())

In [ ]:
x[:,:utils.last_dimension(x.get_shape()) - 1].eval()

In [ ]:
tf.nn.embedding_lookup(x, tf.shape(x)[1] - 1).eval()

In [ ]:
tf.unpack(x)[-1].eval()

In [ ]:
tf.unpack(x, axis=1)[-1].eval()

In [ ]:
tf.pack(tf.unpack(x, axis=1)[:-1]).eval()

In [ ]:
tf.pack([tf.unpack(x)[-1], tf.unpack(x)[0]]).eval()

In [ ]:
tf.concat(0, [tf.unpack(x)[-1], tf.unpack(x)[0]]).eval()

In [ ]:
utils.last_dimension??

In [ ]:
x.get_shape()[1].value

In [ ]:
tf.zeros([x.get_shape()[0]]).eval()

In [ ]:
tf.zeros([x.get_shape()[0].value]).eval()

In [ ]:
x = tf.constant([1,2,3])
y = tf.constant([1,2])

In [ ]:
(tf.shape(x) > tf.shape(y)).eval()

In [ ]:
tf.cond??

In [ ]:
tf.pack?

In [ ]:
tf.unpack?

In [ ]:
tf.tile?

In [ ]:
tf.pad?

In [ ]:
tf.tile?

In [ ]:
a = tf.constant([[1, 2], [3, 4]])

# Reshape `a` as a vector. -1 means "set this dimension automatically".
a_as_vector = tf.reshape(a, [-1])

print a_as_vector.eval()

# Create another vector containing zeroes to pad `a` to (2 * 3) elements.
zero_padding = tf.zeros([2 * 3] - tf.shape(a_as_vector), dtype=a.dtype)

print zero_padding.eval()

# Concatenate `a_as_vector` with the padding.
a_padded = tf.concat(0, [a_as_vector, zero_padding])

print a_padded.eval()

# Reshape the padded vector to the desired shape.
result = tf.reshape(a_padded, [2, 3])

In [ ]:
result.eval()

In [ ]:
x = tf.constant([1,2, 3, 4, 5])
y = tf.constant([1,2])

In [ ]:
tf.shape(x).eval()

In [ ]:
tf.zeros(tf.shape(x) - tf.shape(y)).eval()

In [ ]:
tf.concat(0, [y, tf.zeros(tf.shape(x) - tf.shape(y), tf.int32)]).eval()

In [ ]:
x, y = tf.cond(
        tf.greater(tf.shape(x)[0], tf.shape(y)[0]), 
        lambda: (x, tf.concat(0, [y, tf.zeros(tf.shape(x) - tf.shape(y), tf.int32)])), 
        lambda: (tf.concat(0, [x, tf.zeros(tf.shape(y) - tf.shape(x), tf.int32)]), y))

In [ ]:
x.eval()

In [ ]:
y.eval()

In [ ]:
 tf.select(comparison, tf.zeros_like(a), a)

In [ ]:
x = tf.constant([[1,2, 3, 4, 5], [2,2,3,4,5]])
y = tf.constant([[1,2],[3,4]])

In [ ]:
tf.zeros([tf.shape(x)[0], tf.shape(x)[1] - tf.shape(y)[1]], tf.int32).eval()

In [ ]:
tf.shape(x).eval()

In [ ]:
tf.zeros(tf.shape(x)).eval()

In [ ]:
u = tf.shape(x)

In [ ]:
u[1] = tf.shape(x)[1] - tf.shape(y)[1]

In [ ]:
delta = (tf.shape(x) - tf.shape(y))
delta.eval()

In [ ]:
tf.shape(y).eval()

In [ ]:
delta_sign = tf.sign(delta)
delta_sign.eval()

In [ ]:
tf.logical_and(tf.cast(tf.shape(y), tf.bool), tf.cast(delta_sign, tf.bool)).eval()

In [ ]:
tf.logical_not(tf.cast(delta_sign, tf.bool)).eval()

In [ ]:
tf.mul(tf.shape(y), tf.cast(tf.logical_not(tf.cast(delta_sign, tf.bool)), tf.int32)).eval()

In [ ]:
tf.add(tf.mul(tf.shape(y), tf.cast(tf.logical_not(tf.cast(delta_sign, tf.bool)), tf.int32)), delta).eval()

In [ ]:
tf.add(tf.mul(tf.shape(x), tf.cast(tf.logical_not(tf.cast(delta_sign, tf.bool)), tf.int32)), delta).eval()

In [ ]:
import melt

In [ ]:
melt.subtract_by_diff(tf.shape(x), tf.shape(y)).eval()

In [1]:
import tensorflow as tf
sess = tf.InteractiveSession()
x = tf.constant([[1,2, 3, 4, 5], [2,2,3,4,5]])
y = tf.constant([[1,2],[3,4], [5, 6]])
print x.eval()
print y.eval()

[[1 2 3 4 5]
 [2 2 3 4 5]]
[[1 2]
 [3 4]
 [5 6]]


In [2]:
import melt

In [3]:
melt.subtract_by_diff(tf.shape(x), tf.shape(y)).eval()

array([1, 3], dtype=int32)

In [4]:
u, v = melt.align_col_padding2d(x, y)
print u.eval()
print v.eval()

[[1 2 3 4 5]
 [2 2 3 4 5]]
[[1 2 0 0 0]
 [3 4 0 0 0]
 [5 6 0 0 0]]


In [6]:
y = tf.constant([[1,2, 3, 4, 5], [2,2,3,4,5]])
x = tf.constant([[1,2],[3,4], [5, 6]])
print x.eval()
print y.eval()
u, v = melt.align_col_padding2d(x, y)
print u.eval()
print v.eval()

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3 4 5]
 [2 2 3 4 5]]
[[1 2 0 0 0]
 [3 4 0 0 0]
 [5 6 0 0 0]]
[[1 2 3 4 5]
 [2 2 3 4 5]]


In [7]:
y = tf.constant([[1,2], [3,4,]])
x = tf.constant([[1,2],[3,4]])
print x.eval()
print y.eval()

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [9]:
u, v = melt.align_col_padding2d(x, y)
print u.eval()
print v.eval()

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [10]:
tf.pad?

In [ ]:
tf.pad(x, [[0, 0], [0, 2]]).eval()