In [1]:
import tensorflow as tf
sess = tf.InteractiveSession()

In [2]:
x = tf.constant([[1,2,3,4],[5,6,7,8],[0,0,0,0], [1,1,1,1]], tf.float32)

In [3]:
tf.nn.embedding_lookup(x, [0, 2]).eval()

array([[ 1.,  2.,  3.,  4.],
       [ 0.,  0.,  0.,  0.]], dtype=float32)

In [4]:
tf.nn.embedding_lookup(x, [[0, 2], [1,3]]).eval()

array([[[ 1.,  2.,  3.,  4.],
        [ 0.,  0.,  0.,  0.]],

       [[ 5.,  6.,  7.,  8.],
        [ 1.,  1.,  1.,  1.]]], dtype=float32)

In [5]:
tf.nn.embedding_lookup(x, [[0, 2], [1,3]]).eval().shape

(2, 2, 4)

In [6]:
tf.nn.embedding_lookup(x, [0, 2]).eval().shape

(2, 4)

In [7]:
dir(tf.contrib)

['__builtins__',
 '__doc__',
 '__file__',
 '__name__',
 '__package__',
 '__path__',
 'absolute_import',
 'bayesflow',
 'copy_graph',
 'distributions',
 'division',
 'factorization',
 'framework',
 'graph_editor',
 'grid_rnn',
 'layers',
 'learn',
 'linear_optimizer',
 'lookup',
 'losses',
 'metrics',
 'opt',
 'print_function',
 'quantization',
 'rnn',
 'session_bundle',
 'slim',
 'tensor_forest',
 'testing',
 'util']

In [8]:
from tensorflow.contrib import skflow

ImportError: cannot import name skflow

In [9]:
from tensorflow.contrib import learn as skflow

In [10]:
help(skflow.ops.split_squeeze)

Help on function split_squeeze in module tensorflow.contrib.framework.python.framework.deprecation:

split_squeeze(*args, **kwargs)
    Splits input on given dimension and then squeezes that dimension. (deprecated)
    
    THIS FUNCTION IS DEPRECATED. It will be removed after 2016-08-01.
    Instructions for updating:
    Please use tf.unpack instead.
    
      Args:
        dim: Dimension to split and squeeze on.
        num_split: integer, the number of ways to split.
        tensor_in: Input tensor of shape [N1, N2, .. Ndim, .. Nx].
    
      Returns:
        List of tensors [N1, N2, .. Ndim-1, Ndim+1, .. Nx].



In [11]:
import tensorflow as tf

In [12]:
tf.__version__

'0.10.0rc0'

In [13]:
help(tf.unpack)

Help on function unpack in module tensorflow.python.ops.array_ops:

unpack(value, num=None, axis=0, name='unpack')
    Unpacks the given dimension of a rank-`R` tensor into rank-`(R-1)` tensors.
    
    Unpacks `num` tensors from `value` by chipping it along the `axis` dimension.
    If `num` is not specified (the default), it is inferred from `value`'s shape.
    If `value.shape[axis]` is not known, `ValueError` is raised.
    
    For example, given a tensor of shape `(A, B, C, D)`;
    
    If `axis == 0` then the i'th tensor in `output` is the slice
      `value[i, :, :, :]` and each tensor in `output` will have shape `(B, C, D)`.
      (Note that the dimension unpacked along is gone, unlike `split`).
    
    If `axis == 1` then the i'th tensor in `output` is the slice
      `value[:, i, :, :]` and each tensor in `output` will have shape `(A, C, D)`.
    Etc.
    
    This is the opposite of pack.  The numpy equivalent is
    
        tf.unpack(x, n) = list(x)
    
    Args:
    

In [50]:
l1  = tf.unpack(x, 2)

In [51]:
print l1
print len(l1)

[<tf.Tensor 'unpack_17:0' shape=(4,) dtype=float32>, <tf.Tensor 'unpack_17:1' shape=(4,) dtype=float32>]
2


In [53]:
u = tf.unpack(x)
print u
print len(u)

[<tf.Tensor 'unpack_19:0' shape=(4,) dtype=float32>, <tf.Tensor 'unpack_19:1' shape=(4,) dtype=float32>, <tf.Tensor 'unpack_19:2' shape=(4,) dtype=float32>, <tf.Tensor 'unpack_19:3' shape=(4,) dtype=float32>]
4


In [54]:
l1 = l1 + u
print l1
print len(l1)

[<tf.Tensor 'unpack_17:0' shape=(4,) dtype=float32>, <tf.Tensor 'unpack_17:1' shape=(4,) dtype=float32>, <tf.Tensor 'unpack_19:0' shape=(4,) dtype=float32>, <tf.Tensor 'unpack_19:1' shape=(4,) dtype=float32>, <tf.Tensor 'unpack_19:2' shape=(4,) dtype=float32>, <tf.Tensor 'unpack_19:3' shape=(4,) dtype=float32>]
6


In [55]:
l2 = tf.pack(l1)

In [56]:
l2

<tf.Tensor 'pack_6:0' shape=(6, 4) dtype=float32>

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.]], dtype=float32)

In [59]:
x

<tf.Tensor 'Const:0' shape=(4, 4) dtype=float32>

In [63]:
tf.argmax(x, 0).eval()

array([1, 1, 1, 1])

In [64]:
tf.argmax(x, 1).eval()

array([3, 3, 0, 0])

In [65]:
help(tf.arg_max)

Help on function arg_max in module tensorflow.python.ops.gen_math_ops:

arg_max(input, dimension, name=None)
    Returns the index with the largest value across dimensions of a tensor.
    
    Args:
      input: A `Tensor`. Must be one of the following types: `float32`, `float64`, `int64`, `int32`, `uint8`, `uint16`, `int16`, `int8`, `complex64`, `complex128`, `qint8`, `quint8`, `qint32`, `half`.
      dimension: A `Tensor` of type `int32`.
        int32, 0 <= dimension < rank(input).  Describes which dimension
        of the input Tensor to reduce across. For vectors, use dimension = 0.
      name: A name for the operation (optional).
    
    Returns:
      A `Tensor` of type `int64`.



In [73]:
tf.nn.top_k(x, 2)[1][:,1].eval()

array([2, 2, 1, 1], dtype=int32)

In [74]:
tf.nn.top_k(x, 2)[1].eval()

array([[3, 2],
       [3, 2],
       [0, 1],
       [0, 1]], dtype=int32)

In [75]:
help(tf.nn.top_k)

Help on function top_k in module tensorflow.python.ops.nn_ops:

top_k(input, k=1, sorted=True, name=None)
    Finds values and indices of the `k` largest entries for the last dimension.
    
    If the input is a vector (rank-1), finds the `k` largest entries in the vector
    and outputs their values and indices as vectors.  Thus `values[j]` is the
    `j`-th largest entry in `input`, and its index is `indices[j]`.
    
    For matrices (resp. higher rank input), computes the top `k` entries in each
    row (resp. vector along the last dimension).  Thus,
    
        values.shape = indices.shape = input.shape[:-1] + [k]
    
    If two elements are equal, the lower-index element appears first.
    
    Args:
      input: 1-D or higher `Tensor` with last dimension at least `k`.
      k: 0-D `int32` `Tensor`.  Number of top elements to look for along the last
        dimension (along each row for matrices).
      sorted: If true the resulting `k` elements will be sorted by the values in

In [76]:
import numpy as np
help(np.random.choice)

Help on built-in function choice:

choice(...)
    choice(a, size=None, replace=True, p=None)
    
    Generates a random sample from a given 1-D array
    
            .. versionadded:: 1.7.0
    
    Parameters
    -----------
    a : 1-D array-like or int
        If an ndarray, a random sample is generated from its elements.
        If an int, the random sample is generated as if a was np.arange(n)
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    replace : boolean, optional
        Whether the sample is with or without replacement
    p : 1-D array-like, optional
        The probabilities associated with each entry in a.
        If not given the sample assumes a uniform distribution over all
        entries in a.
    
    Returns
    --------
    samples : 1-D ndarray, shape (size,)
        The generated ran

In [77]:
help(tf.reduce_sum)

Help on function reduce_sum in module tensorflow.python.ops.math_ops:

reduce_sum(input_tensor, reduction_indices=None, keep_dims=False, name=None)
    Computes the sum of elements across dimensions of a tensor.
    
    Reduces `input_tensor` along the dimensions given in `reduction_indices`.
    Unless `keep_dims` is true, the rank of the tensor is reduced by 1 for each
    entry in `reduction_indices`. If `keep_dims` is true, the reduced dimensions
    are retained with length 1.
    
    If `reduction_indices` has no entries, all dimensions are reduced, and a
    tensor with a single element is returned.
    
    For example:
    
    ```python
    # 'x' is [[1, 1, 1]
    #         [1, 1, 1]]
    tf.reduce_sum(x) ==> 6
    tf.reduce_sum(x, 0) ==> [2, 2, 2]
    tf.reduce_sum(x, 1) ==> [3, 3]
    tf.reduce_sum(x, 1, keep_dims=True) ==> [[3], [3]]
    tf.reduce_sum(x, [0, 1]) ==> 6
    ```
    
    Args:
      input_tensor: The tensor to reduce. Should have numeric type.
      reducti

In [79]:
dir(tf.nn)

['__all__',
 '__builtins__',
 '__doc__',
 '__file__',
 '__name__',
 '__package__',
 '_compute_sampled_logits',
 '_sum_rows',
 'absolute_import',
 'all_candidate_sampler',
 'array_ops',
 'atrous_conv2d',
 'avg_pool',
 'avg_pool3d',
 'avg_pool3d_grad',
 'batch_norm_with_global_normalization',
 'batch_normalization',
 'bias_add',
 'bias_add_grad',
 'bias_add_v1',
 'bidirectional_dynamic_rnn',
 'bidirectional_rnn',
 'candidate_sampling_ops',
 'collections',
 'common_shapes',
 'compute_accidental_hits',
 'constant_op',
 'control_flow_ops',
 'conv1d',
 'conv2d',
 'conv2d_backprop_filter',
 'conv2d_backprop_input',
 'conv2d_transpose',
 'conv3d',
 'conv3d_backprop_filter',
 'conv3d_backprop_filter_v2',
 'conv3d_backprop_input',
 'conv3d_backprop_input_v2',
 'conv3d_transpose',
 'ctc_beam_search_decoder',
 'ctc_greedy_decoder',
 'ctc_loss',
 'data_flow_ops',
 'depthwise_conv2d',
 'depthwise_conv2d_native',
 'depthwise_conv2d_native_backprop_filter',
 'depthwise_conv2d_native_backprop_input',
 

In [80]:
help(tf.nn.xw_plus_b)

Help on function xw_plus_b in module tensorflow.python.ops.nn_ops:

xw_plus_b(x, weights, biases, name=None)
    Computes matmul(x, weights) + biases.
    
    Args:
      x: a 2D tensor.  Dimensions typically: batch, in_units
      weights: a 2D tensor.  Dimensions typically: in_units, out_units
      biases: a 1D tensor.  Dimensions: out_units
      name: A name for the operation (optional).  If not specified
        "xw_plus_b" is used.
    
    Returns:
      A 2-D Tensor computing matmul(x, weights) + biases.
      Dimensions typically: batch, out_units.



In [81]:
help(tf.Variable)

Help on class Variable in module tensorflow.python.ops.variables:

class Variable(__builtin__.object)
 |  See the [Variables How To](../../how_tos/variables/index.md) for a high
 |  level overview.
 |  
 |  A variable maintains state in the graph across calls to `run()`. You add a
 |  variable to the graph by constructing an instance of the class `Variable`.
 |  
 |  The `Variable()` constructor requires an initial value for the variable,
 |  which can be a `Tensor` of any type and shape. The initial value defines the
 |  type and shape of the variable. After construction, the type and shape of
 |  the variable are fixed. The value can be changed using one of the assign
 |  methods.
 |  
 |  If you want to change the shape of a variable later you have to use an
 |  `assign` Op with `validate_shape=False`.
 |  
 |  Just like any `Tensor`, variables created with `Variable()` can be used as
 |  inputs for other Ops in the graph. Additionally, all the operators
 |  overloaded for the `Tens

In [92]:
x.eval()

array([[  6.,  12.,  18.,  24.],
       [ 22.,  28.,  34.,  40.],
       [  2.,   4.,   6.,   8.],
       [  6.,   8.,  10.,  12.]], dtype=float32)

In [90]:
x = x*2

In [91]:
x.eval()

array([[  6.,  12.,  18.,  24.],
       [ 22.,  28.,  34.,  40.],
       [  2.,   4.,   6.,   8.],
       [  6.,   8.,  10.,  12.]], dtype=float32)

In [89]:
x.eval()

array([[  3.,   6.,   9.,  12.],
       [ 11.,  14.,  17.,  20.],
       [  1.,   2.,   3.,   4.],
       [  3.,   4.,   5.,   6.]], dtype=float32)

In [86]:
y = tf.constant([1,2,3,4], tf.float32)

In [87]:
x = x + y

In [88]:
x.eval()

array([[  3.,   6.,   9.,  12.],
       [ 11.,  14.,  17.,  20.],
       [  1.,   2.,   3.,   4.],
       [  3.,   4.,   5.,   6.]], dtype=float32)

In [93]:
x = tf.constant([[1,2,3,4],[5,6,7,8],[0,0,0,0], [1,1,1,1]], tf.float32)

In [94]:
x = x + tf.reshape(y, [4, 1])

In [95]:
x.eval()

array([[  2.,   3.,   4.,   5.],
       [  7.,   8.,   9.,  10.],
       [  3.,   3.,   3.,   3.],
       [  5.,   5.,   5.,   5.]], dtype=float32)

In [96]:
tf.reduce_sum(x).eval()

80.0

In [97]:
help(tf.reduce_mean)

Help on function reduce_mean in module tensorflow.python.ops.math_ops:

reduce_mean(input_tensor, reduction_indices=None, keep_dims=False, name=None)
    Computes the mean of elements across dimensions of a tensor.
    
    Reduces `input_tensor` along the dimensions given in `reduction_indices`.
    Unless `keep_dims` is true, the rank of the tensor is reduced by 1 for each
    entry in `reduction_indices`. If `keep_dims` is true, the reduced dimensions
    are retained with length 1.
    
    If `reduction_indices` has no entries, all dimensions are reduced, and a
    tensor with a single element is returned.
    
    For example:
    
    ```python
    # 'x' is [[1., 1.]
    #         [2., 2.]]
    tf.reduce_mean(x) ==> 1.5
    tf.reduce_mean(x, 0) ==> [1.5, 1.5]
    tf.reduce_mean(x, 1) ==> [1.,  2.]
    ```
    
    Args:
      input_tensor: The tensor to reduce. Should have numeric type.
      reduction_indices: The dimensions to reduce. If `None` (the default),
        reduces a

In [98]:
tf.reduce_mean(x, 1).eval()

array([ 3.5,  8.5,  3. ,  5. ], dtype=float32)

In [101]:
tf.reduce_mean(x, -1).eval()

array([ 3.5,  8.5,  3. ,  5. ], dtype=float32)

In [102]:
tf.reduce_sum(x, 1).eval()

array([ 14.,  34.,  12.,  20.], dtype=float32)

In [103]:
(x / tf.reduce_sum(x, 1)).eval()

array([[ 0.14285715,  0.0882353 ,  0.33333334,  0.25      ],
       [ 0.5       ,  0.23529412,  0.75      ,  0.5       ],
       [ 0.21428572,  0.0882353 ,  0.25      ,  0.15000001],
       [ 0.35714287,  0.14705883,  0.41666666,  0.25      ]], dtype=float32)

In [104]:
x[:,1].eval()

array([ 3.,  8.,  3.,  5.], dtype=float32)

In [106]:
tf.slice(x, [0, 0], [-1, 1]).eval()

array([[ 2.],
       [ 7.],
       [ 3.],
       [ 5.]], dtype=float32)

In [108]:
(tf.slice(x, [0, 0], [-1, 1]) / tf.reduce_sum(x, 1)).eval()

array([[ 0.14285715,  0.05882353,  0.16666667,  0.1       ],
       [ 0.5       ,  0.20588236,  0.58333331,  0.34999999],
       [ 0.21428572,  0.0882353 ,  0.25      ,  0.15000001],
       [ 0.35714287,  0.14705883,  0.41666666,  0.25      ]], dtype=float32)

In [109]:
help(tf.reduce_sum)

Help on function reduce_sum in module tensorflow.python.ops.math_ops:

reduce_sum(input_tensor, reduction_indices=None, keep_dims=False, name=None)
    Computes the sum of elements across dimensions of a tensor.
    
    Reduces `input_tensor` along the dimensions given in `reduction_indices`.
    Unless `keep_dims` is true, the rank of the tensor is reduced by 1 for each
    entry in `reduction_indices`. If `keep_dims` is true, the reduced dimensions
    are retained with length 1.
    
    If `reduction_indices` has no entries, all dimensions are reduced, and a
    tensor with a single element is returned.
    
    For example:
    
    ```python
    # 'x' is [[1, 1, 1]
    #         [1, 1, 1]]
    tf.reduce_sum(x) ==> 6
    tf.reduce_sum(x, 0) ==> [2, 2, 2]
    tf.reduce_sum(x, 1) ==> [3, 3]
    tf.reduce_sum(x, 1, keep_dims=True) ==> [[3], [3]]
    tf.reduce_sum(x, [0, 1]) ==> 6
    ```
    
    Args:
      input_tensor: The tensor to reduce. Should have numeric type.
      reducti

In [110]:
help(tf.nn.sparse_softmax_cross_entropy_with_logits)

Help on function sparse_softmax_cross_entropy_with_logits in module tensorflow.python.ops.nn_ops:

sparse_softmax_cross_entropy_with_logits(logits, labels, name=None)
    Computes sparse softmax cross entropy between `logits` and `labels`.
    
    Measures the probability error in discrete classification tasks in which the
    classes are mutually exclusive (each entry is in exactly one class).  For
    example, each CIFAR-10 image is labeled with one and only one label: an image
    can be a dog or a truck, but not both.
    
    **NOTE:**  For this operation, the probability of a given label is considered
    exclusive.  That is, soft classes are not allowed, and the `labels` vector
    must provide a single specific index for the true class for each row of
    `logits` (each minibatch entry).  For soft softmax classification with
    a probability distribution for each entry, see
    `softmax_cross_entropy_with_logits`.
    
    **WARNING:** This op expects unscaled logits, since i

In [111]:
help(tf.nn.in_top_k)

Help on function in_top_k in module tensorflow.python.ops.gen_nn_ops:

in_top_k(predictions, targets, k, name=None)
    Says whether the targets are in the top `K` predictions.
    
    This outputs a `batch_size` bool array, an entry `out[i]` is `true` if the
    prediction for the target class is among the top `k` predictions among
    all predictions for example `i`. Note that the behavior of `InTopK` differs
    from the `TopK` op in its handling of ties; if multiple classes have the
    same prediction value and straddle the top-`k` boundary, all of those
    classes are considered to be in the top `k`.
    
    More formally, let
    
      \\(predictions_i\\) be the predictions for all classes for example `i`,
      \\(targets_i\\) be the target class for example `i`,
      \\(out_i\\) be the output for example `i`,
    
    $$out_i = predictions_{i, targets_i} \in TopKIncludingTies(predictions_i)$$
    
    Args:
      predictions: A `Tensor` of type `float32`.
        A `batch

In [ ]:
tf.train.Int64List