In [1]:
import tensorflow as tf
sess = tf.InteractiveSession()
x = tf.constant([
        [1,2,3,4],
        [5,6,7,8],
        [0,0,0,0], 
        [1,1,1,1]], tf.float32)
print x.eval()
print x.eval().shape

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 0.  0.  0.  0.]
 [ 1.  1.  1.  1.]]
(4, 4)


In [2]:
u = tf.nn.embedding_lookup(x, [0, 2])
print u.eval()
print u.eval().shape

[[ 1.  2.  3.  4.]
 [ 0.  0.  0.  0.]]
(2, 4)


In [3]:
index =  tf.constant([[0,2], 
          [1,3],
          [1,0]])
v = tf.nn.embedding_lookup(x, index)
print v.eval()
print v.eval().shape

[[[ 1.  2.  3.  4.]
  [ 0.  0.  0.  0.]]

 [[ 5.  6.  7.  8.]
  [ 1.  1.  1.  1.]]

 [[ 5.  6.  7.  8.]
  [ 1.  2.  3.  4.]]]
(3, 2, 4)


In [4]:
import melt

In [5]:
melt.embedding_lookup(x, index, 1).eval()

array([[ 0.5,  1. ,  1.5,  2. ],
       [ 3. ,  3.5,  4. ,  4.5],
       [ 3. ,  4. ,  5. ,  6. ]], dtype=float32)

In [6]:
melt.batch_embedding_lookup(x, index).eval()

array([[ 0.5,  1. ,  1.5,  2. ],
       [ 3. ,  3.5,  4. ,  4.5],
       [ 3. ,  4. ,  5. ,  6. ]], dtype=float32)

In [7]:
tf.shape(u).eval()

array([2, 4], dtype=int32)

In [8]:
from tensorflow.contrib.layers.python.layers import utils

In [9]:
len(u.get_shape())

2

In [10]:
melt.batch_masked_embedding_lookup_sum(x, index).eval()

array([[ 0.,  0.,  0.,  0.],
       [ 6.,  7.,  8.,  9.],
       [ 5.,  6.,  7.,  8.]], dtype=float32)

In [11]:
melt.batch_masked_embedding_lookup_mean(x, index).eval()

array([[ 0. ,  0. ,  0. ,  0. ],
       [ 3. ,  3.5,  4. ,  4.5],
       [ 5. ,  6. ,  7. ,  8. ]], dtype=float32)

In [12]:
#tf.expand_dims?

In [13]:
tf.gather(x, 3).eval()

array([ 1.,  1.,  1.,  1.], dtype=float32)

In [14]:
tf.gather(x, 5).eval()

InvalidArgumentError: indices = 5 is not in [0, 4)
	 [[Node: Gather_1 = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Const, Gather_1/indices)]]
Caused by op u'Gather_1', defined at:
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/usr/lib/python2.7/site-packages/traitlets/config/application.py", line 589, in launch_instance
    app.start()
  File "/usr/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 442, in start
    ioloop.IOLoop.instance().start()
  File "/usr/lib64/python2.7/site-packages/zmq/eventloop/ioloop.py", line 151, in start
    super(ZMQIOLoop, self).start()
  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 883, in start
    handler_func(fd_obj, events)
  File "/usr/lib64/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 433, in _handle_events
    self._handle_recv()
  File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 465, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
    callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 391, in execute_request
    user_expressions, allow_stdin)
  File "/usr/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 199, in do_execute
    shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2723, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2831, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-2c7a7c9551ed>", line 1, in <module>
    tf.gather(x, 5).eval()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 980, in gather
    validate_indices=validate_indices, name=name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2310, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1232, in __init__
    self._traceback = _extract_stack()
