In [1]:
import tensorflow as tf

In [2]:
help(tf.expand_dims)

Help on function expand_dims in module tensorflow.python.ops.gen_array_ops:

expand_dims(input, dim, name=None)
    Inserts a dimension of 1 into a tensor's shape.
    
    Given a tensor `input`, this operation inserts a dimension of 1 at the
    dimension index `dim` of `input`'s shape. The dimension index `dim` starts at
    zero; if you specify a negative number for `dim` it is counted backward from
    the end.
    
    This operation is useful if you want to add a batch dimension to a single
    element. For example, if you have a single image of shape `[height, width,
    channels]`, you can make it a batch of 1 image with `expand_dims(image, 0)`,
    which will make the shape `[1, height, width, channels]`.
    
    Other examples:
    
    ```prettyprint
    # 't' is a tensor of shape [2]
    shape(expand_dims(t, 0)) ==> [1, 2]
    shape(expand_dims(t, 1)) ==> [2, 1]
    shape(expand_dims(t, -1)) ==> [2, 1]
    
    # 't2' is a tensor of shape [2, 3, 5]
    shape(expand_dims(t

In [4]:
import tensorflow as tf
sess = tf.InteractiveSession()

In [12]:
t = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)

In [19]:
tf.expand_dims(t, 1).eval()

array([[[ 1.,  2.,  3.]],

       [[ 4.,  5.,  6.]]], dtype=float32)

In [14]:
t.eval().shape

(2, 3)

In [18]:
tf.expand_dims(t, 1).eval().shape

(2, 1, 3)

In [17]:
tf.concat(1, [tf.zeros([2,1]), t]).eval()

array([[ 0.,  1.,  2.,  3.],
       [ 0.,  4.,  5.,  6.]], dtype=float32)

In [20]:
t[:,1].eval()

array([ 2.,  5.], dtype=float32)

In [26]:
tf.reshape(t[:,1],[-1, 1]).eval()

array([[ 2.],
       [ 5.]], dtype=float32)

In [25]:
tf.reshape(t[:,1],[-1, 1]).eval().shape

(2, 1)

In [34]:
tf.expand_dims(t[:,1],1).eval()

array([[ 2.],
       [ 5.]], dtype=float32)

In [28]:
tf.expand_dims(t[:,1],1).eval().shape

(2, 1)

In [29]:
tf.gather(t, 1).eval()

array([ 4.,  5.,  6.], dtype=float32)

In [35]:
tf.slice(t, [0, 1], [-1, 1]).eval()

array([[ 2.,  3.],
       [ 5.,  6.]], dtype=float32)

In [32]:
help(tf.slice)

Help on function slice in module tensorflow.python.ops.array_ops:

slice(input_, begin, size, name=None)
    Extracts a slice from a tensor.
    
    This operation extracts a slice of size `size` from a tensor `input` starting
    at the location specified by `begin`. The slice `size` is represented as a
    tensor shape, where `size[i]` is the number of elements of the 'i'th dimension
    of `input` that you want to slice. The starting location (`begin`) for the
    slice is represented as an offset in each dimension of `input`. In other
    words, `begin[i]` is the offset into the 'i'th dimension of `input` that you
    want to slice from.
    
    `begin` is zero-based; `size` is one-based. If `size[i]` is -1,
    all remaining elements in dimension i are included in the
    slice. In other words, this is equivalent to setting:
    
    `size[i] = input.dim_size(i) - begin[i]`
    
    This operation requires that:
    
    `0 <= begin[i] <= begin[i] + size[i] <= Di  for i in [0, n

In [38]:
tf.expand_dims(tf.range(0, 10, 1), 1).eval()

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]], dtype=int32)

In [43]:
tf.pack([3, 2]).eval().shape

(2,)

In [42]:
help(tf.pack)

Help on function pack in module tensorflow.python.ops.array_ops:

pack(values, axis=0, name='pack')
    Packs a list of rank-`R` tensors into one rank-`(R+1)` tensor.
    
    Packs the list of tensors in `values` into a tensor with rank one higher than
    each tensor in `values`, by packing them along the `axis` dimension.
    Given a list of length `N` of tensors of shape `(A, B, C)`;
    
    if `axis == 0` then the `output` tensor will have the shape `(N, A, B, C)`.
    if `axis == 1` then the `output` tensor will have the shape `(A, N, B, C)`.
    Etc.
    
    For example:
    
    ```prettyprint
    # 'x' is [1, 4]
    # 'y' is [2, 5]
    # 'z' is [3, 6]
    pack([x, y, z]) => [[1, 4], [2, 5], [3, 6]]  # Pack along first dim.
    pack([x, y, z], axis=1) => [[1, 2, 3], [4, 5, 6]]
    ```
    
    This is the opposite of unpack.  The numpy equivalent is
    
        tf.pack([x, y, z]) = np.asarray([x, y, z])
    
    Args:
      values: A list of `Tensor` objects with the same sh

In [44]:
help(tf.sparse_to_dense)

Help on function sparse_to_dense in module tensorflow.python.ops.sparse_ops:

sparse_to_dense(sparse_indices, output_shape, sparse_values, default_value=0, validate_indices=True, name=None)
    Converts a sparse representation into a dense tensor.
    
    Builds an array `dense` with shape `output_shape` such that
    
    ```python
    # If sparse_indices is scalar
    dense[i] = (i == sparse_indices ? sparse_values : default_value)
    
    # If sparse_indices is a vector, then for each i
    dense[sparse_indices[i]] = sparse_values[i]
    
    # If sparse_indices is an n by d matrix, then for each i in [0, n)
    dense[sparse_indices[i][0], ..., sparse_indices[i][d-1]] = sparse_values[i]
    ```
    
    All other values in `dense` are set to `default_value`.  If `sparse_values`
    is a scalar, all sparse indices are set to this single value.
    
    Indices should be sorted in lexicographic order, and indices must not
    contain any repeats. If `validate_indices` is True, these

In [23]:
x = tf.zeros([1])

In [24]:
x.eval()

array([ 0.], dtype=float32)

In [25]:
x = tf.zeros([1,])

In [26]:
x.eval()

array([ 0.], dtype=float32)

In [27]:
x = tf.zeros(1)

In [28]:
x.eval()

array([ 0.], dtype=float32)