In [1]:
import tensorflow as tf
sess = tf.InteractiveSession()

In [4]:
x = tf.zeros([3])
y = x + 1

In [5]:
y_ = sess.run(y)

In [6]:
print y_

[ 1.  1.  1.]


In [7]:
y_ = sess.run(y)
print y_

[ 1.  1.  1.]


In [8]:
y_ = sess.run(y, {x: y_})

In [9]:
print y_

[ 2.  2.  2.]
