In [1]:
import tensorflow as tf

In [2]:
sess = tf.InteractiveSession()

In [3]:
x = tf.constant([[1,2],[3,4],[5,6],[7,8]])

In [4]:
x.eval()

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]], dtype=int32)

In [7]:
x[0,:].eval()

array([1, 2], dtype=int32)

In [8]:
tf.gather(x, 1).eval()

array([3, 4], dtype=int32)

In [9]:
help(tf.gather)

Help on function gather in module tensorflow.python.ops.gen_array_ops:

gather(params, indices, validate_indices=None, name=None)
    Gather slices from `params` according to `indices`.
    
    `indices` must be an integer tensor of any dimension (usually 0-D or 1-D).
    Produces an output tensor with shape `indices.shape + params.shape[1:]` where:
    
        # Scalar indices
        output[:, ..., :] = params[indices, :, ... :]
    
        # Vector indices
        output[i, :, ..., :] = params[indices[i], :, ... :]
    
        # Higher rank indices
        output[i, ..., j, :, ... :] = params[indices[i, ..., j], :, ..., :]
    
    If `indices` is a permutation and `len(indices) == params.shape[0]` then
    this operation will permute `params` accordingly.
    
    <div style="width:70%; margin:auto; margin-bottom:10px; margin-top:20px;">
    <img style="width:100%" src="../../images/Gather.png" alt>
    </div>
    
    Args:
      params: A `Tensor`.
      indices: A `Tensor`. 

In [10]:
tf.gather(x, [0,1]).eval()

array([[1, 2],
       [3, 4]], dtype=int32)

In [14]:
tf.slice(x, [0, 0],[3,-1]).eval()

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

In [16]:
tf.gather(x, range(3)).eval()

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

In [13]:
help(tf.gather_nd)

Help on function gather_nd in module tensorflow.python.ops.gen_array_ops:

gather_nd(params, indices, name=None)
    Gather values or slices from `params` according to `indices`.
    
    `params` is a Tensor of rank `R` and `indices` is a Tensor of rank `M`.
    
    `indices` must be integer tensor, containing indices into `params`.
    It must be shape `[d_0, ..., d_N, R]` where `0 < R <= M`.
    
    The innermost dimension of `indices` (with length `R`) corresponds to
    indices into elements (if `R = M`) or slices (if `R < M`) along the `N`th
    dimension of `params`.
    
    Produces an output tensor with shape
    
        [d_0, ..., d_{n-1}, params.shape[R], ..., params.shape[M-1]].
    
    Some examples below.
    
    Simple indexing into a matrix:
    
        indices = [[0, 0], [1, 1]]
        params = [['a', 'b'], ['c', 'd']]
        output = ['a', 'd']
    
    Slice indexing into a matrix:
    
        indices = [[1], [0]]
        params = [['a', 'b'], ['c', 'd']]
 

In [17]:
help(tf.slice)

Help on function slice in module tensorflow.python.ops.array_ops:

slice(input_, begin, size, name=None)
    Extracts a slice from a tensor.
    
    This operation extracts a slice of size `size` from a tensor `input` starting
    at the location specified by `begin`. The slice `size` is represented as a
    tensor shape, where `size[i]` is the number of elements of the 'i'th dimension
    of `input` that you want to slice. The starting location (`begin`) for the
    slice is represented as an offset in each dimension of `input`. In other
    words, `begin[i]` is the offset into the 'i'th dimension of `input` that you
    want to slice from.
    
    `begin` is zero-based; `size` is one-based. If `size[i]` is -1,
    all remaining elements in dimension i are included in the
    slice. In other words, this is equivalent to setting:
    
    `size[i] = input.dim_size(i) - begin[i]`
    
    This operation requires that:
    
    `0 <= begin[i] <= begin[i] + size[i] <= Di  for i in [0, n