In [3]:
import tensorflow as tf

In [4]:
sess = tf.InteractiveSession()

In [5]:
x = tf.constant([[1., 2., 3.], [1.,2.,3.]])

In [6]:
y = tf.constant([[1., 1., 1.], [2., 2., 2.]])

In [7]:
tf.nn.embedding_lookup(y, [0]).eval()

array([[ 1.,  1.,  1.]], dtype=float32)

In [8]:
x.eval().shape

(2, 3)

In [9]:
(tf.add(x, tf.nn.embedding_lookup(y, [0]) * 9) / 10).eval()

array([[ 1.        ,  1.10000002,  1.20000005],
       [ 1.        ,  1.10000002,  1.20000005]], dtype=float32)

In [10]:
x[0,0].eval()

1.0

In [72]:
x = tf.constant([[1., 2., 3.], [1.,2.,3.], [3. , 2., 1.]])

In [73]:
x[:,0].eval()

array([ 1.,  1.,  3.], dtype=float32)

In [74]:
x.eval()
x[0:2,:].eval()

array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.]], dtype=float32)

In [75]:
x[:2,:].eval()

array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.]], dtype=float32)

In [37]:
tf.gather(x[:,0], [0,1]).eval()

array([ 1.,  1.], dtype=float32)

In [43]:
x[:,0][0:2].eval()

array([ 1.,  1.], dtype=float32)

In [53]:
x[0:2,0].eval()

array([ 1.,  1.], dtype=float32)

In [13]:
tf.gather(x, range(2)).eval()

array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.]], dtype=float32)

In [14]:
y = tf.gather(x, range(2))

In [15]:
x[2,:].eval() #y[2,:] will fail

array([ 3.,  2.,  1.], dtype=float32)

In [18]:
tf.slice(x, [0, 0], [2, 1]).eval()

array([[ 1.],
       [ 1.]], dtype=float32)

In [17]:
tf.squeeze(tf.slice(x, [0, 0], [2, 1])).eval()

array([ 1.,  1.], dtype=float32)

In [ ]:
tf.squeeze(tf.slice(x, [0, 0], [2, 1])).eval().shape

In [22]:
y = tf.constant([[[1., 2., 3.], [1.,2.,3.], [3. , 2., 1.]],[[1., 2., 3.], [1.,2.,3.], [3. , 2., 1.]]])

In [23]:
y.eval()

array([[[ 1.,  2.,  3.],
        [ 1.,  2.,  3.],
        [ 3.,  2.,  1.]],

       [[ 1.,  2.,  3.],
        [ 1.,  2.,  3.],
        [ 3.,  2.,  1.]]], dtype=float32)

In [24]:
y.eval().shape

(2, 3, 3)

In [25]:
y[:,0,:].eval()

array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.]], dtype=float32)

In [26]:
y[:,0,:].eval().shape

(2, 3)

In [28]:
u = y[:,0,0]

In [29]:
u.eval()

array([ 1.,  1.], dtype=float32)

In [31]:
u[1].eval()

1.0

In [32]:
y[:,0,0][1].eval()

1.0

In [52]:
y[0:1,:,:].eval()

array([[[ 1.,  2.,  3.],
        [ 1.,  2.,  3.],
        [ 3.,  2.,  1.]]], dtype=float32)

In [62]:
x = tf.constant([[1,2,3]])
x.eval().shape

(1, 3)

In [65]:
y = tf.constant([[3,2,1]])
y.eval().shape

(1, 3)

In [69]:
tf.concat([x,y], 0)

ValueError: Shapes (2, 1, 3) and () are incompatible

In [68]:
help(tf.concat)

Help on function concat in module tensorflow.python.ops.array_ops:

concat(concat_dim, values, name='concat')
    Concatenates tensors along one dimension.
    
    Concatenates the list of tensors `values` along dimension `concat_dim`.  If
    `values[i].shape = [D0, D1, ... Dconcat_dim(i), ...Dn]`, the concatenated
    result has shape
    
        [D0, D1, ... Rconcat_dim, ...Dn]
    
    where
    
        Rconcat_dim = sum(Dconcat_dim(i))
    
    That is, the data from the input tensors is joined along the `concat_dim`
    dimension.
    
    The number of dimensions of the input tensors must match, and all dimensions
    except `concat_dim` must be equal.
    
    For example:
    
    ```python
    t1 = [[1, 2, 3], [4, 5, 6]]
    t2 = [[7, 8, 9], [10, 11, 12]]
    tf.concat(0, [t1, t2]) ==> [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
    tf.concat(1, [t1, t2]) ==> [[1, 2, 3, 7, 8, 9], [4, 5, 6, 10, 11, 12]]
    
    # tensor t3 with shape [2, 3]
    # tensor t4 with shape [

In [70]:
t1 = tf.constant([[1, 2, 3], [4, 5, 6]])
t2 = tf.constant([[7, 8, 9], [10, 11, 12]])
tf.concat(0, [t1, t2]).eval()

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)