In [1]:
import tensorflow as tf
sess = tf.InteractiveSession()

In [2]:
values = tf.constant([[[ 2.44353771,  0.65329778, -2.08763194, -0.64653987,  0.50398952,
        -0.66223699,  2.24809909, -0.60570312, -0.74135935,  2.5471828 ,
         2.91521454, -1.30316925,  0.81219608],
       [-0.06042745, -1.43421483,  1.98799515,  0.46523282,  1.17595863,
         0.43213287, -0.33148676,  0.36731029, -2.01692128,  0.75370973,
         2.03620768, -0.97226971, -0.90286547]]])

In [3]:
values.eval()

array([[[ 2.44353771,  0.65329778, -2.08763194, -0.64653987,  0.50398952,
         -0.66223699,  2.24809909, -0.60570312, -0.74135935,  2.5471828 ,
          2.91521454, -1.30316925,  0.81219608],
        [-0.06042745, -1.43421483,  1.98799515,  0.46523282,  1.17595863,
          0.43213287, -0.33148676,  0.36731029, -2.01692128,  0.75370973,
          2.03620768, -0.97226971, -0.90286547]]], dtype=float32)

In [4]:
values.eval().shape

(1, 2, 13)

In [5]:
zeros = tf.zeros_like(values, dtype=tf.float32)

In [6]:
values2 = tf.concat([values, zeros], 1)

In [7]:
values2.eval()

array([[[ 2.44353771,  0.65329778, -2.08763194, -0.64653987,  0.50398952,
         -0.66223699,  2.24809909, -0.60570312, -0.74135935,  2.5471828 ,
          2.91521454, -1.30316925,  0.81219608],
        [-0.06042745, -1.43421483,  1.98799515,  0.46523282,  1.17595863,
          0.43213287, -0.33148676,  0.36731029, -2.01692128,  0.75370973,
          2.03620768, -0.97226971, -0.90286547],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ]]], dtype=float32)

In [8]:
values2.eval().shape

(1, 4, 13)

In [9]:
import melt

tensorflow_version: 0.12.head


In [10]:
with tf.variable_scope('abc') as scope:
    keys = tf.contrib.layers.linear(
            values, 13, biases_initializer=None, scope=scope)
    print keys
    #scope.reuse_variables()
    keys2 = tf.contrib.layers.linear(
        values2, 13, biases_initializer=None, scope=scope)
    print keys2

Tensor("abc/Reshape_1:0", shape=(1, 2, 13), dtype=float32)
Tensor("abc/Reshape_3:0", shape=(1, 4, 13), dtype=float32)


In [11]:
sess.run(tf.global_variables_initializer())

In [12]:
keys.eval()

array([[[-2.76704907,  1.07119632,  0.49521279,  0.92081642,  1.47548401,
          0.0156966 , -1.08358371, -0.32566541, -0.23117727, -2.00929308,
          0.8186326 , -1.48907399, -1.38828707],
        [-0.94829035,  0.58998978,  1.3966794 ,  2.14945579,  2.82302332,
          1.32140112, -0.06452473, -0.12929353,  1.43046021,  0.1826469 ,
          0.83877879, -1.51018238, -1.02547741]]], dtype=float32)

In [13]:
keys.eval().shape

(1, 2, 13)

In [14]:
keys2.eval()

array([[[-2.76704907,  1.07119632,  0.49521279,  0.92081642,  1.47548401,
          0.0156966 , -1.08358371, -0.32566541, -0.23117727, -2.00929308,
          0.8186326 , -1.48907399, -1.38828707],
        [-0.94829035,  0.58998978,  1.3966794 ,  2.14945579,  2.82302332,
          1.32140112, -0.06452473, -0.12929353,  1.43046021,  0.1826469 ,
          0.83877879, -1.51018238, -1.02547753],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ]]], dtype=float32)

In [15]:
for item in tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES):
    print item

Tensor("abc/weights/read:0", shape=(13, 13), dtype=float32)
