In [1]:
import tensorflow as tf


In [2]:
help( tf.train.string_input_producer)

Help on function string_input_producer in module tensorflow.python.training.input:

string_input_producer(string_tensor, num_epochs=None, shuffle=True, seed=None, capacity=32, shared_name=None, name=None)
    Output strings (e.g. filenames) to a queue for an input pipeline.
    
    Args:
      string_tensor: A 1-D string tensor with the strings to produce.
      num_epochs: An integer (optional). If specified, `string_input_producer`
        produces each string from `string_tensor` `num_epochs` times before
        generating an `OutOfRange` error. If not specified,
        `string_input_producer` can cycle through the strings in `string_tensor`
        an unlimited number of times.
      shuffle: Boolean. If true, the strings are randomly shuffled within each
        epoch.
      seed: An integer (optional). Seed used if shuffle == True.
      capacity: An integer. Sets the queue capacity.
      shared_name: (optional). If set, this queue will be shared under the given
        name 

In [3]:
help(tf.nn.embedding_lookup_sparse)

Help on function embedding_lookup_sparse in module tensorflow.python.ops.embedding_ops:

embedding_lookup_sparse(params, sp_ids, sp_weights, partition_strategy='mod', name=None, combiner='mean')
    Computes embeddings for the given ids and weights.
    
    This op assumes that there is at least one id for each row in the dense tensor
    represented by sp_ids (i.e. there are no rows with empty features), and that
    all the indices of sp_ids are in canonical row-major order.
    
    It also assumes that all id values lie in the range [0, p0), where p0
    is the sum of the size of params along dimension 0.
    
    Args:
      params: A single tensor representing the complete embedding tensor,
        or a list of P tensors all of same shape except for the first dimension,
        representing sharded embedding tensors.
      sp_ids: N x M SparseTensor of int64 ids (typically from FeatureValueToId),
        where N is typically batch size and M is arbitrary.
      sp_weights: eithe

In [4]:
help(tf.parse_example)

Help on function parse_example in module tensorflow.python.ops.parsing_ops:

parse_example(serialized, features, name=None, example_names=None)
    Parses `Example` protos into a `dict` of tensors.
    
    Parses a number of serialized [`Example`]
    (https://www.tensorflow.org/code/tensorflow/core/example/example.proto)
    protos given in `serialized`.
    
    `example_names` may contain descriptive names for the corresponding serialized
    protos. These may be useful for debugging purposes, but they have no effect on
    the output. If not `None`, `example_names` must be the same length as `serialized`.
    
    This op parses serialized examples into a dictionary mapping keys to `Tensor`
    and `SparseTensor` objects. `features` is a dict from keys to `VarLenFeature`
    and `FixedLenFeature` objects. Each `VarLenFeature` is mapped to a
    `SparseTensor`, and each `FixedLenFeature` is mapped to a `Tensor`.
    
    Each `VarLenFeature` maps to a `SparseTensor` of the specifie

In [5]:
import random

In [7]:
help(random.randint)

Help on method randint in module random:

randint(self, a, b) method of random.Random instance
    Return random integer in range [a, b], including both end points.



In [8]:
print 'abc'

abc


In [9]:
from multiprocessing import Process, Manager

In [10]:
def f(n):
    n.value += 1

In [13]:
d = {}
p = []

In [14]:
for i in range(5):
    d[i] = Manager().Value('i',0)
    p.append(Process(target=f, args=(d[i],)))
    p[i].start()

In [15]:
 for q in p:
        q.join()

In [16]:
   for i in d:
        d[i] = d[i].value

In [17]:
print d

{0: 1, 1: 1, 2: 1, 3: 1, 4: 1}


In [18]:
from multiprocessing import Process, Manager

In [19]:
help(Manager)

Help on function Manager in module multiprocessing:

Manager()
    Returns a manager associated with a running server process
    
    The managers methods such as `Lock()`, `Condition()` and `Queue()`
    can be used to create shared objects.



In [20]:
m = Manager()

In [21]:
help(m.Array)

Help on method Array in module multiprocessing.managers:

Array(self, *args, **kwds) method of multiprocessing.managers.SyncManager instance



In [22]:
d = m.dict()

In [23]:
help(d)

Help on DictProxy in module multiprocessing.managers object:

class DictProxy(BaseProxy)
 |  Method resolution order:
 |      DictProxy
 |      BaseProxy
 |      __builtin__.object
 |  
 |  Methods defined here:
 |  
 |  __contains__(self, *args, **kwds)
 |  
 |  __delitem__(self, *args, **kwds)
 |  
 |  __getitem__(self, *args, **kwds)
 |  
 |  __len__(self, *args, **kwds)
 |  
 |  __setitem__(self, *args, **kwds)
 |  
 |  clear(self, *args, **kwds)
 |  
 |  copy(self, *args, **kwds)
 |  
 |  get(self, *args, **kwds)
 |  
 |  has_key(self, *args, **kwds)
 |  
 |  items(self, *args, **kwds)
 |  
 |  keys(self, *args, **kwds)
 |  
 |  pop(self, *args, **kwds)
 |  
 |  popitem(self, *args, **kwds)
 |  
 |  setdefault(self, *args, **kwds)
 |  
 |  update(self, *args, **kwds)
 |  
 |  values(self, *args, **kwds)
 |  
 |  ----------------------------------------------------------------------
 |  Methods inherited from BaseProxy:
 |  
 |  __deepcopy__(self, memo)
 |  
 |  __init__(self, toke

In [24]:
d[3] =2

In [27]:
print d[3]

2


In [28]:
print d.values()

[2]


In [29]:
d[4] = 3

In [30]:
print d.values()

[2, 3]


In [35]:
import tensorflow as tf
sess = tf.InteractiveSession()
a = tf.constant([[[0, 0, 1], [0,1,1]],[[1, 0, 1], [1, 1, 1]]])
b = tf.constant([[0, 0, 2], [1, 0, 2]])

Exception AssertionError: AssertionError() in <bound method InteractiveSession.__del__ of <tensorflow.python.client.session.InteractiveSession object at 0x5f02a90>> ignored


In [34]:
a.eval().shape

(2, 2, 3)

In [201]:
b.eval().shape
tf.shape(b)[1].eval()

3

In [209]:
input =  tf.constant([[[1, 1, 1], [2, 2, 2]],
            [[3, 3, 3], [4, 4, 4]],
             [[5, 5, 5], [6, 6, 6]]])
print input.eval().shape
print tf.shape(input)[2].eval()
#print tf.slice(input, [1, 0, 0], [1, 1, tf.shape(input)[2]]).eval() 
print tf.slice(input, [1, 0, 0], [1, 2, -1]).eval()
                                           
print tf.slice(input, [1, 0, 0], [2, 1, -1]).eval()
                                          

(3, 2, 3)
3
[[[3 3 3]
  [4 4 4]]]
[[[3 3 3]]

 [[5 5 5]]]


In [77]:
b2 = tf.slice(b, [0, 0], [2, 3])

In [78]:
print b2.eval()

[[0 0 2]
 [1 0 2]]


In [49]:
a2 = tf.slice(a, [0, 0, 0], [1, 1, 3])

In [50]:
print a2.eval()

[[[0 0 1]]]


In [51]:
print b2.eval().shape

(1, 3)


In [53]:
print (b2 + a2).eval()

[[[0 0 3]]]


In [80]:
tf.nn.embedding_lookup(input, b2).eval().shape

(2, 3, 2, 3)

In [59]:
tf.nn.embedding_lookup(input, tf.reshape(b2, [3,])).eval()

array([[[1, 1, 1],
        [2, 2, 2]],

       [[1, 1, 1],
        [2, 2, 2]],

       [[5, 5, 5],
        [6, 6, 6]]], dtype=int32)

In [60]:
b2.eval().shape

(1, 3)

In [61]:
tf.reshape(b2, [3,]).eval().shape

(3,)

In [69]:
tf.reduce_mean(tf.cast(tf.nn.embedding_lookup(input, tf.reshape(b2, [3,])), tf.float32), 1).eval()

array([[ 1.5,  1.5,  1.5],
       [ 1.5,  1.5,  1.5],
       [ 5.5,  5.5,  5.5]], dtype=float32)

In [67]:
help(tf.cast)

Help on function cast in module tensorflow.python.ops.math_ops:

cast(x, dtype, name=None)
    Casts a tensor to a new type.
    
    The operation casts `x` (in case of `Tensor`) or `x.values`
    (in case of `SparseTensor`) to `dtype`.
    
    For example:
    
    ```python
    # tensor `a` is [1.8, 2.2], dtype=tf.float
    tf.cast(a, tf.int32) ==> [1, 2]  # dtype=tf.int32
    ```
    
    Args:
      x: A `Tensor` or `SparseTensor`.
      dtype: The destination type.
      name: A name for the operation (optional).
    
    Returns:
      A `Tensor` or `SparseTensor` with same shape as `x`.
    
    Raises:
      TypeError: If `x` cannot be cast to the `dtype`.



In [75]:
a = tf.constant([[[1,2,3], [4, 5, 6]],[[2,2,2], [3,3,3]]])
tf.reduce_sum(a, 1).eval()

array([[5, 7, 9],
       [5, 5, 5]], dtype=int32)

In [85]:
x = tf.constant([[1,1,1], [2,2,2], [3,3,3], [4,4,4]])
print x.eval()
print x.eval().shape

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]
(4, 3)


In [83]:
tf.nn.embedding_lookup(x, b2).eval().shape

(2, 3, 3)

In [87]:
b = tf.constant([[0, 0, 2], [1, 0, 2], [0, 0, 0]])
b = tf.slice(b, [0, 0], [2, 3])
print b.eval()
print b.eval().shape

[[0 0 2]
 [1 0 2]]
(2, 3)


In [88]:
tf.nn.embedding_lookup(x, b).eval()


array([[[1, 1, 1],
        [1, 1, 1],
        [3, 3, 3]],

       [[2, 2, 2],
        [1, 1, 1],
        [3, 3, 3]]], dtype=int32)

In [90]:
tf.nn.embedding_lookup(x, b).eval().shape

(2, 3, 3)

In [110]:
u = tf.cast(tf.nn.embedding_lookup(x, b), tf.float32)

In [111]:
v = tf.reduce_mean(u, 1)

In [112]:
v.eval()

array([[ 1.66666663,  1.66666663,  1.66666663],
       [ 2.        ,  2.        ,  2.        ]], dtype=float32)

In [113]:
v.eval().shape

(2, 3)

In [115]:
c = tf.constant([[[0, 0, 2], [1, 0, 2]], [[0, 0, 0], [1,1,1]], [[0, 0, 0], [1,1,1]]])

In [116]:
c.eval().shape

(3, 2, 3)

In [117]:
tf.nn.embedding_lookup(x, c).eval()

array([[[[1, 1, 1],
         [1, 1, 1],
         [3, 3, 3]],

        [[2, 2, 2],
         [1, 1, 1],
         [3, 3, 3]]],


       [[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]]],


       [[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]]]], dtype=int32)

In [118]:
u = tf.cast(tf.nn.embedding_lookup(x, c), tf.float32)
u.eval().shape

(3, 2, 3, 3)

In [104]:
v = tf.reduce_mean(u, 2)

In [105]:
v.eval()

array([[[ 1.66666663,  1.66666663,  1.66666663],
        [ 2.        ,  2.        ,  2.        ]],

       [[ 1.        ,  1.        ,  1.        ],
        [ 2.        ,  2.        ,  2.        ]]], dtype=float32)

In [106]:
v.eval().shape

(2, 2, 3)

In [119]:
help(tf.reduce_sum)

Help on function reduce_sum in module tensorflow.python.ops.math_ops:

reduce_sum(input_tensor, reduction_indices=None, keep_dims=False, name=None)
    Computes the sum of elements across dimensions of a tensor.
    
    Reduces `input_tensor` along the dimensions given in `reduction_indices`.
    Unless `keep_dims` is true, the rank of the tensor is reduced by 1 for each
    entry in `reduction_indices`. If `keep_dims` is true, the reduced dimensions
    are retained with length 1.
    
    If `reduction_indices` has no entries, all dimensions are reduced, and a
    tensor with a single element is returned.
    
    For example:
    
    ```python
    # 'x' is [[1, 1, 1]
    #         [1, 1, 1]]
    tf.reduce_sum(x) ==> 6
    tf.reduce_sum(x, 0) ==> [2, 2, 2]
    tf.reduce_sum(x, 1) ==> [3, 3]
    tf.reduce_sum(x, 1, keep_dims=True) ==> [[3], [3]]
    tf.reduce_sum(x, [0, 1]) ==> 6
    ```
    
    Args:
      input_tensor: The tensor to reduce. Should have numeric type.
      reducti

In [125]:
norm = tf.sqrt(tf.reduce_sum(tf.square(tf.constant([[1,2,3]])), 0, keep_dims=True))
norm.eval()

InvalidArgumentError: No OpKernel was registered to support Op 'Sqrt' with these attrs
	 [[Node: Sqrt_3 = Sqrt[T=DT_INT32](Sum_9)]]
Caused by op u'Sqrt_3', defined at:
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/usr/lib/python2.7/site-packages/traitlets/config/application.py", line 589, in launch_instance
    app.start()
  File "/usr/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 442, in start
    ioloop.IOLoop.instance().start()
  File "/usr/lib64/python2.7/site-packages/zmq/eventloop/ioloop.py", line 151, in start
    super(ZMQIOLoop, self).start()
  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 883, in start
    handler_func(fd_obj, events)
  File "/usr/lib64/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 433, in _handle_events
    self._handle_recv()
  File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 465, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
    callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 391, in execute_request
    user_expressions, allow_stdin)
  File "/usr/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 199, in do_execute
    shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2723, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2825, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-125-3a778d29c483>", line 1, in <module>
    norm = tf.sqrt(tf.reduce_sum(tf.square(tf.constant([[1,2,3]])), 0, keep_dims=True))
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1664, in sqrt
    return _op_def_lib.apply_op("Sqrt", x=x, name=name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 693, in apply_op
    op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2177, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1161, in __init__
    self._traceback = _extract_stack()


In [130]:
x = tf.constant([[1,2, 3],[3,4,5]])
print x.eval().shape
y = tf.constant([[1], [2], [3]])
print y.eval().shape
z = tf.matmul(x, y)
z.eval()

(2, 3)
(3, 1)


array([[14],
       [26]], dtype=int32)

In [167]:
x = tf.constant([[[1,2, 3],[1,2,4]], [[3,4,5],[4,5,6]]])
print x.eval().shape
y = tf.constant([[1, 2], [2, 2], [3, 3]])
print y.eval().shape
#z = tf.matmul(x, y)
#z.eval()
#u = tf.constant([[0], [0]])
#u = None
l = []
for i in range(2):
    print tf.slice(x, [0, i, 0], [2, 1, 3]).eval()
    z = tf.matmul(tf.reshape(tf.slice(x, [0, i, 0], [2, 1, 3]), [2, 3]), y)
    print 'z:', z.eval()
    #u += z
    #if u == None:
    #    u = z
    #else:
    #    u = tf.concat(1, [u, z])
    #print 'u:', u.eval()
    l.append(z)

u = tf.concat(0, l)
print u.eval()
print u.eval().shape

(2, 2, 3)
(3, 2)
[[[1 2 3]]

 [[3 4 5]]]
z: [[14 15]
 [26 29]]
[[[1 2 4]]

 [[4 5 6]]]
z: [[17 18]
 [32 36]]
[[14 15]
 [26 29]
 [17 18]
 [32 36]]
(4, 2)


In [157]:
for i in range(2):
    print tf.slice(u, [0, i * 2], [2, 2]).eval()

[[14 15]
 [26 29]]
[[17 18]
 [32 36]]


In [153]:
print tf.unpack(u)[0].eval()

[14 15 17 18]


In [150]:
help(tf.unpack)

Help on function unpack in module tensorflow.python.ops.array_ops:

unpack(value, num=None, name='unpack')
    Unpacks the outer dimension of a rank-`R` tensor into rank-`(R-1)` tensors.
    
    Unpacks `num` tensors from `value` along the first dimension.
    If `num` is not specified (the default), it is inferred from `value`'s shape.
    If `value.shape[0]` is not known, `ValueError` is raised.
    
    The ith tensor in `output` is the slice `value[i, ...]`. Each tensor in
    `output` has shape `value.shape[1:]`.
    
    This is the opposite of pack.  The numpy equivalent is
    
        tf.unpack(x, n) = list(x)
    
    Args:
      value: A rank `R > 0` `Tensor` to be unpacked.
      num: An `int`. The first dimension of value. Automatically inferred if
        `None` (the default).
      name: A name for the operation (optional).
    
    Returns:
      The list of `Tensor` objects unpacked from `value`.
    
    Raises:
      ValueError: If `num` is unspecified and cannot be

In [158]:
import tensorflow as tf

B = 2
N = 2
scores = tf.constant([0.5, 0.2, -0.1, 1., -0.5, 0.3])  # shape B * (N+1)

scores = tf.reshape(scores, [B, N+1])

scores_pos = tf.slice(scores, [0, 0], [B, 1])

scores_neg = tf.slice(scores, [0, 1], [B, N])

print scores_pos.eval()

[[ 0.5]
 [ 1. ]]


In [191]:
s = tf.constant([1,2, 3, 4])
s2 = tf.constant([2, 3, 4, 5])
s3 = tf.constant([3, 4, 5, 6])
a = tf.reshape(s, [4,1])
b = tf.reshape(s2, [4, 1])
c = tf.reshape(s3, [4, 1])
x = tf.concat(1,[a, b, c])
print x.eval()

scores_pos = tf.slice(x, [0, 0], [4, 1])
print scores_pos.eval()
scores_neg = tf.slice(x, [0, 1], [4, 2])
loss_matrix = tf.maximum(0, 1 - scores_pos + scores_neg)  # we could also use tf.nn.relu here
print loss_matrix.eval()
#loss = tf.reduce_mean(tf.reduce_sum(loss_matrix, 1))
loss = tf.reduce_mean(tf.cast(loss_matrix, tf.float32))
print loss.eval()

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
[[1]
 [2]
 [3]
 [4]]
[[2 3]
 [2 3]
 [2 3]
 [2 3]]
2.5


In [175]:
x = tf.reshape(x, [4, 3])

In [176]:
x.eval()

array([[1, 2, 3],
       [4, 2, 3],
       [4, 5, 3],
       [4, 5, 6]], dtype=int32)

In [ ]:
loss_matrix = tf.maximum(0., 1. - scores_pos + scores_neg)  # we could also use tf.nn.relu here
loss = tf.reduce_sum(loss_matrix)

In [192]:
a = tf.constant([[1,2,3], [4,5,6]])
b = tf.constant([[1,1,1], [2,2,2]])
print a.eval().shape
print b.eval().shape

(2, 3)
(2, 3)


In [196]:
norm_a = tf.sqrt(tf.reduce_sum(tf.square(a), 1, keep_dims=True))
print norm_a.eval()

InvalidArgumentError: No OpKernel was registered to support Op 'Sqrt' with these attrs
	 [[Node: Sqrt_4 = Sqrt[T=DT_INT32](Sum_15)]]
Caused by op u'Sqrt_4', defined at:
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/usr/lib/python2.7/site-packages/traitlets/config/application.py", line 589, in launch_instance
    app.start()
  File "/usr/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 442, in start
    ioloop.IOLoop.instance().start()
  File "/usr/lib64/python2.7/site-packages/zmq/eventloop/ioloop.py", line 151, in start
    super(ZMQIOLoop, self).start()
  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 883, in start
    handler_func(fd_obj, events)
  File "/usr/lib64/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 433, in _handle_events
    self._handle_recv()
  File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 465, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
    callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 391, in execute_request
    user_expressions, allow_stdin)
  File "/usr/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 199, in do_execute
    shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2723, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2825, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-193-d1cf0847badf>", line 1, in <module>
    a = tf.sqrt(tf.reduce_sum(tf.square(a), 1, keep_dims=True))
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1664, in sqrt
    return _op_def_lib.apply_op("Sqrt", x=x, name=name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 693, in apply_op
    op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2177, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1161, in __init__
    self._traceback = _extract_stack()
