In [1]:
import tensorflow as tf

In [2]:
sess = tf.InteractiveSession()

In [3]:
x = tf.constant([[1,2,3,4], [2,2,3,4]])

In [4]:
print x

Tensor("Const:0", shape=(2, 4), dtype=int32)


In [5]:
x.eval()

array([[1, 2, 3, 4],
       [2, 2, 3, 4]], dtype=int32)

In [6]:
tf.shape(x)

<tf.Tensor 'Shape:0' shape=(2,) dtype=int32>

In [7]:
tf.shape(x)[0]

<tf.Tensor 'Squeeze:0' shape=() dtype=int32>

In [8]:
tf.shape(x)[0].eval()

2

In [9]:
y = tf.zeros_like(x)

In [10]:
y

<tf.Tensor 'zeros_like:0' shape=(2, 4) dtype=int32>

In [11]:
z = tf.zeros([tf.shape(x)[0], tf.shape(x)[1]])

In [12]:
z.eval()

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]], dtype=float32)

In [15]:
import melt

In [16]:
u = melt.get_weights('a', [3,2])

In [19]:
u.initializer.run()

In [20]:
u.eval()

array([[ 0.00073459, -0.00648577],
       [-0.00450062,  0.01854396],
       [ 0.01223013,  0.00408192]], dtype=float32)

In [21]:
u = melt.get_weights('a', [tf.shape(x)[0], tf.shape(x)[1]])

TypeError: int() argument must be a string or a number, not 'Tensor'

In [22]:
u = tf.zeros([tf.shape(x)[0], tf.shape(x)[1]])

In [24]:
u = tf.get_variable('abc', [2,3], initializer=tf.random_normal_initializer(stddev=1))

In [27]:
u.initializer.run()

In [28]:
u.eval()

array([[-0.27483624,  2.36603093,  2.86235881],
       [-0.55101132, -0.48579755,  1.1522764 ]], dtype=float32)

In [29]:
u = tf.get_variable('abc', [tf.shape(x)[0], tf.shape(x)[1]], initializer=tf.random_normal_initializer(stddev=1))

TypeError: int() argument must be a string or a number, not 'Tensor'

In [30]:
help(tf.get_variable)

Help on function get_variable in module tensorflow.python.ops.variable_scope:

get_variable(name, shape=None, dtype=tf.float32, initializer=None, regularizer=None, trainable=True, collections=None, caching_device=None, partitioner=None, validate_shape=True, custom_getter=None)
    Gets an existing variable with these parameters or create a new one.
    
    This function prefixes the name with the current variable scope
    and performs reuse checks. See the
    [Variable Scope How To](../../how_tos/variable_scope/index.md)
    for an extensive description of how reusing works. Here is a basic example:
    
    ```python
    with tf.variable_scope("foo"):
        v = tf.get_variable("v", [1])  # v.name == "foo/v:0"
        w = tf.get_variable("w", [1])  # w.name == "foo/w:0"
    with tf.variable_scope("foo", reuse=True)
        v1 = tf.get_variable("v")  # The same as v above.
    ```
    
    If initializer is `None` (the default), the default initializer passed in
    the variable sc

In [31]:
help(tf.zeros)

Help on function zeros in module tensorflow.python.ops.array_ops:

zeros(shape, dtype=tf.float32, name=None)
    Creates a tensor with all elements set to zero.
    
    This operation returns a tensor of type `dtype` with shape `shape` and
    all elements set to zero.
    
    For example:
    
    ```python
    tf.zeros([3, 4], int32) ==> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
    ```
    
    Args:
      shape: Either a list of integers, or a 1-D `Tensor` of type `int32`.
      dtype: The type of an element in the resulting `Tensor`.
      name: A name for the operation (optional).
    
    Returns:
      A `Tensor` with all elements set to zero.



In [32]:
from tensorflow.contrib.layers.python.layers import utils

In [33]:
inputs_shape = u.get_shape()

In [36]:
num_input_units = utils.last_dimension(inputs_shape, min_rank=2)

In [37]:
print num_input_units

3


In [38]:
help(utils.last_dimension)

Help on function last_dimension in module tensorflow.contrib.layers.python.layers.utils:

last_dimension(shape, min_rank=1)
    Returns the last dimension of shape while checking it has min_rank.
    
    Args:
      shape: A `TensorShape`.
      min_rank: Integer, minimum rank of shape.
    
    Returns:
      The value of the last dimension.
    
    Raises:
      ValueError: if inputs don't have at least min_rank dimensions, or if the
        last dimension value is not defined.



In [42]:
inputs_shape.dims[-1].eval()

AttributeError: 'Dimension' object has no attribute 'eval'

In [46]:
u = tf.get_variable('abcd',inputs_shape , initializer=tf.random_normal_initializer(stddev=1))

In [47]:
u.initializer.run()

In [48]:
u.eval()

array([[ 1.86671937,  1.86460364, -1.26947176],
       [-0.10570773, -1.12823439, -2.38893604]], dtype=float32)