In [1]:
import tensorflow as tf
sess = tf.InteractiveSession()

In [2]:
x = tf.constant([1.0, 3.0])

In [3]:
tf.nn.softmax(x).eval()

array([ 0.11920291,  0.88079703], dtype=float32)

In [4]:
tf.reduce_sum(tf.nn.softmax(x)).eval()

0.99999994

In [5]:
tf.nn.log_softmax(x).eval()

array([-2.12692809, -0.12692805], dtype=float32)

In [6]:
x = tf.constant([1.0, 3.0, 0.0])

In [7]:
tf.nn.softmax(x).eval()

array([ 0.11419519,  0.8437947 ,  0.04201007], dtype=float32)

In [8]:
tf.nn.log_softmax(x).eval()

array([-2.16984606, -0.16984604, -3.16984606], dtype=float32)

In [9]:
x = tf.constant([1.0, 3.0, 1e-12])

In [10]:
tf.nn.softmax(x).eval()

array([ 0.11419519,  0.8437947 ,  0.04201007], dtype=float32)

In [11]:
x = tf.constant([1.0, 3.0, 1e-13])

In [12]:
tf.nn.softmax(x).eval()

array([ 0.11419519,  0.8437947 ,  0.04201007], dtype=float32)

In [15]:
x = tf.constant([1.0, 3.0, 1e-10])

In [16]:
tf.nn.softmax(x).eval()

array([ 0.11419519,  0.8437947 ,  0.04201007], dtype=float32)

In [23]:
x = tf.constant([1.0, 3.0, 1e-10])

In [24]:
tf.nn.log_softmax(x).eval()

array([-2.16984606, -0.16984604, -3.16984606], dtype=float32)

In [26]:
tf.log(0.11920291).eval()

-2.1269281

In [27]:
tf.log(0.88079703).eval()

-0.12692806