In [1]:
import tensorflow as tf
sess = tf.InteractiveSession()

In [2]:
best_path = tf.constant([[1, 2], [3, 4]])

In [3]:
best_path.eval()

array([[1, 2],
       [3, 4]], dtype=int32)

In [4]:
tf.stack?

In [5]:
tf.stack([best_path] * 5).eval()

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]], dtype=int32)

In [6]:
tf.stack([best_path] * 5).eval().shape

(5, 2, 2)

In [9]:
tf.concat_v2([best_path]*5, 0).eval()

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4]], dtype=int32)

In [10]:
tf.concat(0, [best_path]*5).eval()

Instructions for updating:
This op will be removed after the deprecation date. Please switch to tf.concat_v2().


array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4]], dtype=int32)

In [13]:
tf.gather(tf.concat(0, [best_path]*5), 1).eval()

Instructions for updating:
This op will be removed after the deprecation date. Please switch to tf.concat_v2().


array([3, 4], dtype=int32)

In [14]:
import melt


tensorflow_version: 1.0.0-alpha


In [16]:
melt.first_nrows(tf.concat(0, [best_path]*5),2).eval()

Instructions for updating:
This op will be removed after the deprecation date. Please switch to tf.concat_v2().


array([[1, 2],
       [3, 4]], dtype=int32)

In [17]:
tf.gather?