In [1]:
import tensorflow as tf
sess = tf.InteractiveSession()

a = tf.constant([[1,2,3], [4,5,6]])
b = tf.constant([[1,1,1], [2,2,2]])
a = tf.cast(a, tf.float32)
b = tf.cast(b, tf.float32)
print a.eval().shape
print b.eval().shape

(2, 3)
(2, 3)


In [3]:
u = tf.sqrt(tf.reduce_sum(tf.square(a), 1, keep_dims=True))

In [4]:
u = tf.reduce_sum(tf.square(a), 1, keep_dims=True)

In [5]:
u.eval()

array([[ 14.],
       [ 77.]], dtype=float32)

In [8]:
tf.sqrt(u).eval().shape

(2, 1)

In [9]:
normed_a = a / u

In [10]:
normed_a.eval()

array([[ 0.07142857,  0.14285715,  0.21428572],
       [ 0.05194805,  0.06493507,  0.07792208]], dtype=float32)

In [12]:
normed_a.eval().shape

(2, 3)

In [13]:
x = tf.matmul(b, b, transpose_b=True)

In [14]:
x.eval()

array([[  3.,   6.],
       [  6.,  12.]], dtype=float32)

In [15]:
help(tf.gather)

Help on function gather in module tensorflow.python.ops.gen_array_ops:

gather(params, indices, validate_indices=None, name=None)
    Gather slices from `params` according to `indices`.
    
    `indices` must be an integer tensor of any dimension (usually 0-D or 1-D).
    Produces an output tensor with shape `indices.shape + params.shape[1:]` where:
    
        # Scalar indices
        output[:, ..., :] = params[indices, :, ... :]
    
        # Vector indices
        output[i, :, ..., :] = params[indices[i], :, ... :]
    
        # Higher rank indices
        output[i, ..., j, :, ... :] = params[indices[i, ..., j], :, ..., :]
    
    If `indices` is a permutation and `len(indices) == params.shape[0]` then
    this operation will permute `params` accordingly.
    
    <div style="width:70%; margin:auto; margin-bottom:10px; margin-top:20px;">
    <img style="width:100%" src="../../images/Gather.png" alt>
    </div>
    
    Args:
      params: A `Tensor`.
      indices: A `Tensor`. 

In [19]:
tf.gather(x, 0).eval()

array([ 3.,  6.], dtype=float32)

In [21]:
tf.reduce_sum(tf.mul(x, x), 1).eval().shape

(2,)