In [10]:
import tensorflow as tf
import numpy as np

X = tf.placeholder("float", [4, 3]) # create symbolic variables
B = tf.placeholder("float", [4, 1]) # create symbolic variables

x  = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype = np.float32)
b  = np.array([[1], [2], [3], [4]], dtype = np.float32)

m_b = tf.Variable(tf.zeros([4]), name="sm_b")


Examples = tf.placeholder("int64", [3])

examples = [0, 1, 1]

examples2 = [[0,1], [2, 1]]

lookup = tf.nn.embedding_lookup(X, Examples)
lookup2 = tf.nn.embedding_lookup(B, examples)

lookup3 = tf.nn.embedding_lookup(m_b, examples)
sampled_b_vec = tf.reshape(lookup3, [3])

lookup_mean = tf.reduce_mean(lookup, 0, keep_dims=True)


lookup_2example = tf.nn.embedding_lookup(x, examples2)
lookup_2example_mean = tf.reduce_mean(lookup_2example, 1, keep_dims=False)

#lookup_sparse = tf.nn.embedding_lookup_sparse(x, examples2, None)


init = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init)

result, mean_ = sess.run([lookup, lookup_mean], feed_dict={X: x, Examples : examples})
print result 
print result.shape

print 'mean is: ', mean_ 

print 'lookup2 results:'
print sess.run(lookup2, feed_dict={B: b, Examples : examples})

print sess.run(lookup3, feed_dict = {Examples : examples})

print sess.run(sampled_b_vec, feed_dict = {Examples : examples})
print sess.run(sampled_b_vec, feed_dict = {Examples : examples}).shape


print 'lookup 2example'
print sess.run(lookup_2example)
print 'lookup_2example_mean'
print sess.run(lookup_2example_mean)
#print 'lookup sparse mean'
#print sess.run(lookup_sparse)


[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 4.  5.  6.]]
(3, 3)
mean is:  [[ 3.  4.  5.]]
lookup2 results:
[[ 1.]
 [ 2.]
 [ 2.]]
[ 0.  0.  0.]
[ 0.  0.  0.]
(3,)
lookup 2example
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [ 4.  5.  6.]]]
lookup_2example_mean
[[ 2.5  3.5  4.5]
 [ 5.5  6.5  7.5]]


In [1]:
import tensorflow as tf
sess = tf.InteractiveSession()

In [2]:
x = tf.constant([[1,2,3,0],[4,5,6,0], [7,8,9,0]])

In [3]:
tf.nn.embedding_lookup(x, [1,2]).eval()

array([[4, 5, 6, 0],
       [7, 8, 9, 0]], dtype=int32)

In [4]:
x.eval().shape

(3, 4)

In [5]:
tf.nn.embedding_lookup(x, [1,2]).eval().shape

(2, 4)

In [6]:
tf.nn.embedding_lookup(x, [[1],[2]]).eval()

array([[[4, 5, 6, 0]],

       [[7, 8, 9, 0]]], dtype=int32)

In [7]:
help(tf.fill)

Help on function fill in module tensorflow.python.ops.gen_array_ops:

fill(dims, value, name=None)
    Creates a tensor filled with a scalar value.
    
    This operation creates a tensor of shape `dims` and fills it with `value`.
    
    For example:
    
    ```prettyprint
    # Output tensor has shape [2, 3].
    fill([2, 3], 9) ==> [[9, 9, 9]
                         [9, 9, 9]]
    ```
    
    Args:
      dims: A `Tensor` of type `int32`.
        1-D. Represents the shape of the output tensor.
      value: A `Tensor`. 0-D (scalar). Value to fill the returned tensor.
      name: A name for the operation (optional).
    
    Returns:
      A `Tensor`. Has the same type as `value`.



In [9]:
tf.fill([2,3], 9).eval()

array([[9, 9, 9],
       [9, 9, 9]], dtype=int32)

In [10]:
help(tf.zeros)

Help on function zeros in module tensorflow.python.ops.array_ops:

zeros(shape, dtype=tf.float32, name=None)
    Creates a tensor with all elements set to zero.
    
    This operation returns a tensor of type `dtype` with shape `shape` and
    all elements set to zero.
    
    For example:
    
    ```python
    tf.zeros([3, 4], int32) ==> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
    ```
    
    Args:
      shape: Either a list of integers, or a 1-D `Tensor` of type `int32`.
      dtype: The type of an element in the resulting `Tensor`.
      name: A name for the operation (optional).
    
    Returns:
      A `Tensor` with all elements set to zero.



In [11]:
help(tf.nn.sparse_softmax_cross_entropy_with_logits)

Help on function sparse_softmax_cross_entropy_with_logits in module tensorflow.python.ops.nn_ops:

sparse_softmax_cross_entropy_with_logits(logits, labels, name=None)
    Computes sparse softmax cross entropy between `logits` and `labels`.
    
    Measures the probability error in discrete classification tasks in which the
    classes are mutually exclusive (each entry is in exactly one class).  For
    example, each CIFAR-10 image is labeled with one and only one label: an image
    can be a dog or a truck, but not both.
    
    **NOTE:**  For this operation, the probability of a given label is considered
    exclusive.  That is, soft classes are not allowed, and the `labels` vector
    must provide a single specific index for the true class for each row of
    `logits` (each minibatch entry).  For soft softmax classification with
    a probability distribution for each entry, see
    `softmax_cross_entropy_with_logits`.
    
    **WARNING:** This op expects unscaled logits, since i

In [12]:
help(tf.reduce_sum)

Help on function reduce_sum in module tensorflow.python.ops.math_ops:

reduce_sum(input_tensor, reduction_indices=None, keep_dims=False, name=None)
    Computes the sum of elements across dimensions of a tensor.
    
    Reduces `input_tensor` along the dimensions given in `reduction_indices`.
    Unless `keep_dims` is true, the rank of the tensor is reduced by 1 for each
    entry in `reduction_indices`. If `keep_dims` is true, the reduced dimensions
    are retained with length 1.
    
    If `reduction_indices` has no entries, all dimensions are reduced, and a
    tensor with a single element is returned.
    
    For example:
    
    ```python
    # 'x' is [[1, 1, 1]
    #         [1, 1, 1]]
    tf.reduce_sum(x) ==> 6
    tf.reduce_sum(x, 0) ==> [2, 2, 2]
    tf.reduce_sum(x, 1) ==> [3, 3]
    tf.reduce_sum(x, 1, keep_dims=True) ==> [[3], [3]]
    tf.reduce_sum(x, [0, 1]) ==> 6
    ```
    
    Args:
      input_tensor: The tensor to reduce. Should have numeric type.
      reducti

In [13]:
x = tf.constant([[1,2,3,4]])

In [15]:
tf.concat(0, [x] * 4).eval()

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]], dtype=int32)