In [1]:
import tensorflow as tf
import numpy as np

# Create 100 phony x, y data points in NumPy, y = x * 0.1 + 0.3
x_data = np.random.rand(100).astype(np.float32)
y_data = x_data * 0.1 + 0.3

# Try to find values for W and b that compute y_data = W * x_data + b
# (We know that W should be 0.1 and b 0.3, but Tensorflow will
# figure that out for us.)
W = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
b = tf.Variable(tf.zeros([1]))
y = W * x_data + b

# Minimize the mean squared errors.
loss = tf.reduce_mean(tf.square(y - y_data))
optimizer = tf.train.GradientDescentOptimizer(0.5)
train = optimizer.minimize(loss)

# Before starting, initialize the variables.  We will 'run' this first.
init = tf.initialize_all_variables()

# Launch the graph.
sess = tf.Session()
sess.run(init)

# Fit the line.
for step in range(201):
    sess.run(train)
    if step % 20 == 0:
        print(step, sess.run(W), sess.run(b))

# Learns best fit is W: [0.1], b: [0.3]

(0, array([ 0.7933414], dtype=float32), array([-0.14793825], dtype=float32))
(20, array([ 0.31563386], dtype=float32), array([ 0.17733581], dtype=float32))
(40, array([ 0.16490985], dtype=float32), array([ 0.26307577], dtype=float32))
(60, array([ 0.1195391], dtype=float32), array([ 0.28888512], dtype=float32))
(80, array([ 0.10588165], dtype=float32), array([ 0.29665422], dtype=float32))
(100, array([ 0.10177048], dtype=float32), array([ 0.29899287], dtype=float32))
(120, array([ 0.10053294], dtype=float32), array([ 0.29969686], dtype=float32))
(140, array([ 0.10016042], dtype=float32), array([ 0.29990876], dtype=float32))
(160, array([ 0.10004829], dtype=float32), array([ 0.29997253], dtype=float32))
(180, array([ 0.10001455], dtype=float32), array([ 0.29999173], dtype=float32))
(200, array([ 0.1000044], dtype=float32), array([ 0.29999751], dtype=float32))


In [2]:
import tensorflow as tf

# Create a Constant op that produces a 1x2 matrix.  The op is
# added as a node to the default graph.
#
# The value returned by the constructor represents the output
# of the Constant op.
matrix1 = tf.constant([[3., 3.]])

# Create another Constant that produces a 2x1 matrix.
matrix2 = tf.constant([[2.],[2.]])

# Create a Matmul op that takes 'matrix1' and 'matrix2' as inputs.
# The returned value, 'product', represents the result of the matrix
# multiplication.
product = tf.matmul(matrix1, matrix2)

# Launch the default graph.
sess = tf.Session()

# To run the matmul op we call the session 'run()' method, passing 'product'
# which represents the output of the matmul op.  This indicates to the call
# that we want to get the output of the matmul op back.
#
# All inputs needed by the op are run automatically by the session.  They
# typically are run in parallel.
#
# The call 'run(product)' thus causes the execution of three ops in the
# graph: the two constants and matmul.
#
# The output of the op is returned in 'result' as a numpy `ndarray` object.
result = sess.run(product)
print(result)
# ==> [[ 12.]]

# Close the Session when we're done.
sess.close()

[[ 12.]]


In [3]:
sess = tf.InteractiveSession()
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a * b
# We can just use 'c.eval()' without passing 'sess'
print(c.eval())
sess.close()

30.0


In [4]:
sess = tf.Session()
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a * b
# We can just use 'c.eval()' without passing 'sess'
print(c.eval())
sess.close()

ValueError: Cannot evaluate tensor using eval(): No default session is registered. Use `with sess.as_default()` or pass an explicit session to eval(session=sess)

In [5]:
import tensorflow as tf

In [6]:
sess = tf.InteractiveSession()

In [11]:
x = tf.constant(range(12), dtype = tf.float32)

In [12]:
x.eval()

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.], dtype=float32)

In [19]:
keep_prob = tf.constant(0.9)
h_fc1_drop = tf.nn.dropout(x, keep_prob)

In [20]:
h_fc1_drop.eval()

array([  0.        ,   1.11111116,   2.22222233,   3.33333349,
         4.44444466,   5.55555582,   6.66666698,   7.77777815,
         8.88888931,  10.        ,  11.11111164,  12.22222328], dtype=float32)

In [21]:
import tensorflow as tf
import numpy as np

# Data sets
IRIS_TRAINING = "iris_training.csv"
IRIS_TEST = "iris_test.csv"

# Load datasets.
training_set = tf.contrib.learn.datasets.base.load_csv(filename=IRIS_TRAINING, target_dtype=np.int)
test_set = tf.contrib.learn.datasets.base.load_csv(filename=IRIS_TEST, target_dtype=np.int)

x_train, x_test, y_train, y_test = training_set.data, test_set.data, \
  training_set.target, test_set.target

# Build 3 layer DNN with 10, 20, 10 units respectively.
classifier = tf.contrib.learn.DNNClassifier(hidden_units=[10, 20, 10], n_classes=3)

# Fit model.
classifier.fit(x=x_train, y=y_train, steps=200)

# Evaluate accuracy.
accuracy_score = classifier.evaluate(x=x_test, y=y_test)["accuracy"]
print('Accuracy: {0:f}'.format(accuracy_score))

# Classify two new flower samples.
new_samples = np.array(
    [[6.4, 3.2, 4.5, 1.5], [5.8, 3.1, 5.0, 1.7]], dtype=float)
y = classifier.predict(new_samples)
print ('Predictions: {}'.format(str(y)))

IOError: [Errno 2] No such file or directory: 'iris_training.csv'

In [22]:
13//4

3

In [35]:
import tensorflow as tf

B = 2
N = 2
scores = tf.constant([0.5, 0.2, -0.1, 1., -0.5, 0.3])  # shape B * (N+1)

print scores.eval()

scores = tf.reshape(scores, [B, N+1])
print scores.eval()

scores_pos = tf.slice(scores, [0, 0], [B, 1])
print scores_pos.eval()
scores_neg = tf.slice(scores, [0, 1], [B, N])
print scores_neg.eval()
print (scores_pos - scores_neg).eval()
print (1. - scores_pos + scores_neg).eval()
loss_matrix = tf.maximum(0., 1. - scores_pos + scores_neg)  # we could also use tf.nn.relu here
print loss_matrix.eval()
loss = tf.reduce_sum(loss_matrix)
print loss.eval()

[ 0.5         0.2        -0.1         1.         -0.5         0.30000001]
[[ 0.5         0.2        -0.1       ]
 [ 1.         -0.5         0.30000001]]
[[ 0.5]
 [ 1. ]]
[[ 0.2        -0.1       ]
 [-0.5         0.30000001]]
[[ 0.30000001  0.60000002]
 [ 1.5         0.69999999]]
[[ 0.69999999  0.40000001]
 [-0.5         0.30000001]]
[[ 0.69999999  0.40000001]
 [ 0.          0.30000001]]
1.4


In [25]:
scores_pos.eval()

array([[ 0.5],
       [ 1. ]], dtype=float32)

In [26]:
scores_neg.eval()

array([[ 0.2       , -0.1       ],
       [-0.5       ,  0.30000001]], dtype=float32)

In [28]:
help(tf.slice)

Help on function slice in module tensorflow.python.ops.array_ops:

slice(input_, begin, size, name=None)
    Extracts a slice from a tensor.
    
    This operation extracts a slice of size `size` from a tensor `input` starting
    at the location specified by `begin`. The slice `size` is represented as a
    tensor shape, where `size[i]` is the number of elements of the 'i'th dimension
    of `input` that you want to slice. The starting location (`begin`) for the
    slice is represented as an offset in each dimension of `input`. In other
    words, `begin[i]` is the offset into the 'i'th dimension of `input` that you
    want to slice from.
    
    `begin` is zero-based; `size` is one-based. If `size[i]` is -1,
    all remaining elements in dimension i are included in the
    slice. In other words, this is equivalent to setting:
    
    `size[i] = input.dim_size(i) - begin[i]`
    
    This operation requires that:
    
    `0 <= begin[i] <= begin[i] + size[i] <= Di  for i in [0, n

In [51]:
def conv_relu(input, kernel_shape, bias_shape):
    # Create variable named "weights".
    weights = tf.get_variable("weights", kernel_shape,
        initializer=tf.random_normal_initializer())
    # Create variable named "biases".
    biases = tf.get_variable("biases", bias_shape,
        initializer=tf.constant_initializer(0.0))
    conv = tf.nn.conv2d(input, weights,
        strides=[1, 1, 1, 1], padding='SAME')
    return tf.nn.relu(conv + biases)
def my_image_filter(input_images):
    with tf.variable_scope("conv1"):
        # Variables created here will be named "conv1/weights", "conv1/biases".
        relu1 = conv_relu(input_images, [5, 5, 1, 32], [32])
    with tf.variable_scope("conv2"):
        # Variables created here will be named "conv2/weights", "conv2/biases".
        return conv_relu(relu1, [5, 5, 1, 32], [32])

In [52]:
x = tf.constant([[1., 2., 3., 4.],
                 [4., 5., 6., 7.],
                [8., 9., 10., 11.],
                [12.,13.,14.,15.]])

x = tf.reshape(x, [1, 4, 4, 1])  # give a shape accepted by tf.nn.max_pool
#result1 = my_image_filter(x)
#result2 = my_image_filter(x)
# Raises ValueError(... conv1/weights already exists ...)

In [53]:
y = tf.constant([[1., 2., 3., 4.],
                 [4., 5., 6., 7.],
                [8., 9., 10., 11.],
                [12.,13.,14.,15.]])

y = tf.reshape(x, [1, 4, 4, 1])  # give a shape accepted by tf.nn.max_pool
with tf.variable_scope("image_filters") as scope:
    result1 = my_image_filter(y)
    scope.reuse_variables()
    #result2 = my_image_filter(y)

ValueError: Variable image_filters/conv1/weights already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "<ipython-input-39-da151707662a>", line 4, in conv_relu
    initializer=tf.random_normal_initializer())
  File "<ipython-input-39-da151707662a>", line 14, in my_image_filter
    relu1 = conv_relu(input_images, [5, 5, 32, 32], [32])
  File "<ipython-input-43-fa878f4f7f27>", line 8, in <module>
    result1 = my_image_filter(x)


In [2]:
import tensorflow as tf
help(tf.train.batch)

Help on function batch in module tensorflow.python.training.input:

batch(tensor_list, batch_size, num_threads=1, capacity=32, enqueue_many=False, shapes=None, dynamic_pad=False, shared_name=None, name=None)
    Creates batches of tensors in `tensor_list`.
    
    This function is implemented using a queue. A `QueueRunner` for the
    queue is added to the current `Graph`'s `QUEUE_RUNNER` collection.
    
    If `enqueue_many` is `False`, `tensor_list` is assumed to represent a
    single example.  An input tensor with shape `[x, y, z]` will be output
    as a tensor with shape `[batch_size, x, y, z]`.
    
    If `enqueue_many` is `True`, `tensor_list` is assumed to represent a
    batch of examples, where the first dimension is indexed by example,
    and all members of `tensor_list` should have the same size in the
    first dimension.  If an input tensor has shape `[*, x, y, z]`, the
    output will have shape `[batch_size, x, y, z]`.  The `capacity` argument
    controls the how 

In [3]:
help(tf.train.shuffle_batch)

Help on function shuffle_batch in module tensorflow.python.training.input:

shuffle_batch(tensor_list, batch_size, capacity, min_after_dequeue, num_threads=1, seed=None, enqueue_many=False, shapes=None, shared_name=None, name=None)
    Creates batches by randomly shuffling tensors.
    
    This function adds the following to the current `Graph`:
    
    * A shuffling queue into which tensors from `tensor_list` are enqueued.
    * A `dequeue_many` operation to create batches from the queue.
    * A `QueueRunner` to `QUEUE_RUNNER` collection, to enqueue the tensors
      from `tensor_list`.
    
    If `enqueue_many` is `False`, `tensor_list` is assumed to represent a
    single example.  An input tensor with shape `[x, y, z]` will be output
    as a tensor with shape `[batch_size, x, y, z]`.
    
    If `enqueue_many` is `True`, `tensor_list` is assumed to represent a
    batch of examples, where the first dimension is indexed by example,
    and all members of `tensor_list` should ha