In [1]:
import tensorflow as tf
sess = tf.InteractiveSession()

In [49]:
x = tf.constant([[1,2,3, 0, 0], [2, 3, 0, 0, 0]])
print x.eval()

pad = tf.zeros([2, 1])

print tf.concat(1, [pad, tf.cast(x, tf.float32), pad]).eval()

y = tf.zeros_like(x)
z = tf.logical_or(tf.cast(x, tf.bool), tf.cast(y, tf.bool))

print z.eval()

[[1 2 3 0 0]
 [2 3 0 0 0]]
[[ 0.  1.  2.  3.  0.  0.  0.]
 [ 0.  2.  3.  0.  0.  0.  0.]]
[[ True  True  True False False]
 [ True  True False False False]]


In [8]:
tf.boolean_mask(x, z).eval()

array([1, 2, 3, 2, 3], dtype=int32)

In [9]:
help(tf.boolean_mask)

Help on function boolean_mask in module tensorflow.python.ops.array_ops:

boolean_mask(tensor, mask, name='boolean_mask')
    Apply boolean mask to tensor.  Numpy equivalent is `tensor[mask]`.
    
    ```python
    # 1-D example
    tensor = [0, 1, 2, 3]
    mask = [True, False, True, False]
    boolean_mask(tensor, mask) ==> [0, 2]
    ```
    
    In general, `0 < dim(mask) = K <= dim(tensor)`, and `mask`'s shape must match
    the first K dimensions of `tensor`'s shape.  We then have:
      `boolean_mask(tensor, mask)[i, j1,...,jd] = tensor[i1,...,iK,j1,...,jd]`
    where `(i1,...,iK)` is the ith `True` entry of `mask` (row-major order).
    
    Args:
      tensor:  N-D tensor.
      mask:  K-D boolean tensor, K <= N and K must be known statically.
      name:  A name for this operation (optional).
    
    Returns:
      Tensor populated by entries in `tensor` corresponding to `True` values in
        `mask`.
    
    Raises:
      ValueError:  If shapes do not conform.
    
    

In [10]:
help(tf.less)

Help on function less in module tensorflow.python.ops.gen_math_ops:

less(x, y, name=None)
    Returns the truth value of (x < y) element-wise.
    
    Args:
      x: A `Tensor`. Must be one of the following types: `float32`, `float64`, `int32`, `int64`, `uint8`, `int16`, `int8`, `uint16`, `half`.
      y: A `Tensor`. Must have the same type as `x`.
      name: A name for the operation (optional).
    
    Returns:
      A `Tensor` of type `bool`.



In [11]:
tf.greater(x, y).eval()

array([[ True,  True,  True, False, False],
       [ True,  True, False, False, False]], dtype=bool)

In [13]:
z = tf.greater(x, y)

In [14]:
print z.eval()

[[ True  True  True False False]
 [ True  True False False False]]


In [15]:
print z.eval().shape

(2, 5)


In [18]:
print z[1,:].eval()

[ True  True False False False]


In [31]:
x[0,:].eval()

array([1, 2, 3, 0, 0], dtype=int32)

In [37]:
u = x[0,:]

In [38]:
v = z[1,:]

In [39]:
v = tf.cast(v, tf.float32)

In [40]:
u = tf.cast(u, tf.float32)

In [41]:
(u * v).eval()

array([ 1.,  2.,  0.,  0.,  0.], dtype=float32)

In [42]:
help(tf.select)

Help on function select in module tensorflow.python.ops.gen_math_ops:

select(condition, t, e, name=None)
    Selects elements from `t` or `e`, depending on `condition`.
    
    The `t`, and `e` tensors must all have the same shape,
    and the output will also have that shape.  The `condition` tensor
    must be a scalar if `t` and `e` are scalars.  If `t` and `e` are vectors
    or higher rank, then `condition` must be either a vector with size
    matching the first dimension of `t`, or must have the same shape as `t`.
    
    The `condition` tensor acts as a mask that chooses, based on the value at each
    element, whether the corresponding element / row in the output should be
    taken from `t` (if true) or `e` (if false).
    
    If `condition` is a vector and `t` and `e` are higher rank matrices, then
    it chooses which row (outer dimension) to copy from `t` and `e`.
    If `condition` has the same shape as `t` and `e`, then it chooses which
    element to copy from `t` a

In [46]:
help(tf.nn.seq2seq.sequence_loss_by_example)

Help on function sequence_loss_by_example in module tensorflow.python.ops.seq2seq:

sequence_loss_by_example(logits, targets, weights, average_across_timesteps=True, softmax_loss_function=None, name=None)
    Weighted cross-entropy loss for a sequence of logits (per example).
    
    Args:
      logits: List of 2D Tensors of shape [batch_size x num_decoder_symbols].
      targets: List of 1D batch-sized int32 Tensors of the same length as logits.
      weights: List of 1D batch-sized float-Tensors of the same length as logits.
      average_across_timesteps: If set, divide the returned cost by the total
        label weight.
      softmax_loss_function: Function (inputs-batch, labels-batch) -> loss-batch
        to be used instead of the standard softmax (the default if this is None).
      name: Optional name for this operation, default: "sequence_loss_by_example".
    
    Returns:
      1D batch-sized float Tensor: The log-perplexity for each sequence.
    
    Raises:
      ValueE

In [50]:
help(tf.squeeze)

Help on function squeeze in module tensorflow.python.ops.gen_array_ops:

squeeze(input, squeeze_dims=None, name=None)
    Removes dimensions of size 1 from the shape of a tensor.
    
    Given a tensor `input`, this operation returns a tensor of the same type with
    all dimensions of size 1 removed. If you don't want to remove all size 1
    dimensions, you can remove specific size 1 dimensions by specifying
    `squeeze_dims`.
    
    For example:
    
    ```prettyprint
    # 't' is a tensor of shape [1, 2, 1, 3, 1, 1]
    shape(squeeze(t)) ==> [2, 3]
    ```
    
    Or, to remove specific size 1 dimensions:
    
    ```prettyprint
    # 't' is a tensor of shape [1, 2, 1, 3, 1, 1]
    shape(squeeze(t, [2, 4])) ==> [1, 2, 3, 1]
    ```
    
    Args:
      input: A `Tensor`. The `input` to squeeze.
      squeeze_dims: An optional list of `ints`. Defaults to `[]`.
        If specified, only squeezes the dimensions listed. The dimension
        index starts at 0. It is an error to 

In [54]:
x.eval().shape

(2, 5)

In [57]:
tf.zeros([tf.shape(x)[0]]).eval()

array([ 0.,  0.], dtype=float32)

In [58]:
help(tf.zeros)

Help on function zeros in module tensorflow.python.ops.array_ops:

zeros(shape, dtype=tf.float32, name=None)
    Creates a tensor with all elements set to zero.
    
    This operation returns a tensor of type `dtype` with shape `shape` and
    all elements set to zero.
    
    For example:
    
    ```python
    tf.zeros([3, 4], int32) ==> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
    ```
    
    Args:
      shape: Either a list of integers, or a 1-D `Tensor` of type `int32`.
      dtype: The type of an element in the resulting `Tensor`.
      name: A name for the operation (optional).
    
    Returns:
      A `Tensor` with all elements set to zero.

