In [14]:
import tensorflow as tf

help()

AttributeError: 'module' object has no attribute 'get_shape'

In [2]:
help(tf.train.exponential_decay)

Help on function exponential_decay in module tensorflow.python.training.learning_rate_decay:

exponential_decay(learning_rate, global_step, decay_steps, decay_rate, staircase=False, name=None)
    Applies exponential decay to the learning rate.
    
    When training a model, it is often recommended to lower the learning rate as
    the training progresses.  This function applies an exponential decay function
    to a provided initial learning rate.  It requires a `global_step` value to
    compute the decayed learning rate.  You can just pass a TensorFlow variable
    that you increment at each training step.
    
    The function returns the decayed learning rate.  It is computed as:
    
    ```python
    decayed_learning_rate = learning_rate *
                            decay_rate ^ (global_step / decay_steps)
    ```
    
    If the argument `staircase` is `True`, then `global_step / decay_steps` is an
    integer division and the decayed learning rate follows a staircase functio

In [5]:
help(tf.train.shuffle_batch)

Help on function shuffle_batch in module tensorflow.python.training.input:

shuffle_batch(tensors, batch_size, capacity, min_after_dequeue, num_threads=1, seed=None, enqueue_many=False, shapes=None, shared_name=None, name=None)
    Creates batches by randomly shuffling tensors.
    
    This function adds the following to the current `Graph`:
    
    * A shuffling queue into which tensors from `tensors` are enqueued.
    * A `dequeue_many` operation to create batches from the queue.
    * A `QueueRunner` to `QUEUE_RUNNER` collection, to enqueue the tensors
      from `tensors`.
    
    If `enqueue_many` is `False`, `tensors` is assumed to represent a
    single example.  An input tensor with shape `[x, y, z]` will be output
    as a tensor with shape `[batch_size, x, y, z]`.
    
    If `enqueue_many` is `True`, `tensors` is assumed to represent a
    batch of examples, where the first dimension is indexed by example,
    and all members of `tensors` should have the same size in the


In [7]:
import numpy as np

In [8]:
help(np.full)

Help on function full in module numpy.core.numeric:

full(shape, fill_value, dtype=None, order='C')
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `np.int8`.  Default
        is `float`, but will change to `np.array(fill_value).dtype` in a
        future release.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of `fill_value` with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    ones_like : Return an array of ones with shape and type of input.
    emp

In [9]:
help(np.hstack)

Help on function hstack in module numpy.core.shape_base:

hstack(tup)
    Stack arrays in sequence horizontally (column wise).
    
    Take a sequence of arrays and stack them horizontally to make
    a single array. Rebuild arrays divided by `hsplit`.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        All arrays must have the same shape along all but the second axis.
    
    Returns
    -------
    stacked : ndarray
        The array formed by stacking the given arrays.
    
    See Also
    --------
    stack : Join a sequence of arrays along a new axis.
    vstack : Stack arrays in sequence vertically (row wise).
    dstack : Stack arrays in sequence depth wise (along third axis).
    concatenate : Join a sequence of arrays along an existing axis.
    hsplit : Split array along second axis.
    
    Notes
    -----
    Equivalent to ``np.concatenate(tup, axis=1)``
    
    Examples
    --------
    >>> a = np.array((1,2,3))
    >>> b = np.array((2,3,4))
    

In [16]:
sess = tf.InteractiveSession()
a = tf.constant([[1, 2], [3, 4]])
print a.eval()

# Reshape `a` as a vector. -1 means "set this dimension automatically".
a_as_vector = tf.reshape(a, [-1])
print a_as_vector.eval()

# Create another vector containing zeroes to pad `a` to (2 * 3) elements.
zero_padding = tf.zeros([2 * 3] - tf.shape(a_as_vector), dtype=a.dtype)

print tf.shape(a_as_vector).eval()
print zero_padding.eval()

# Concatenate `a_as_vector` with the padding.
a_padded = tf.concat(0, [a_as_vector, zero_padding])

# Reshape the padded vector to the desired shape.
result = tf.reshape(a_padded, [2, 3])

print result.eval()

[[1 2]
 [3 4]]
[1 2 3 4]
[4]
[0 0]
[[1 2 3]
 [4 0 0]]


Exception AssertionError: AssertionError("Nesting violated for default stack of <type 'weakref'> objects",) in <bound method InteractiveSession.__del__ of <tensorflow.python.client.session.InteractiveSession object at 0x6b67d50>> ignored


In [9]:
import tensorflow as tf
sess = tf.InteractiveSession()
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[0,2], [1, 0]])
print a.eval()

c = b[:,1]
print c.eval()

d = a * c
print d.eval()

d = a * tf.expand_dims(b[:,1], 1)
print d.eval()

[[1 2]
 [3 4]]
[2 0]
[[2 0]
 [6 0]]
[[2 4]
 [0 0]]


Exception AssertionError: AssertionError("Nesting violated for default stack of <type 'weakref'> objects",) in <bound method InteractiveSession.__del__ of <tensorflow.python.client.session.InteractiveSession object at 0x324df50>> ignored


In [10]:
help(tf.nn.softmax_cross_entropy_with_logits)

Help on function softmax_cross_entropy_with_logits in module tensorflow.python.ops.nn_ops:

softmax_cross_entropy_with_logits(logits, labels, name=None)
    Computes softmax cross entropy between `logits` and `labels`.
    
    Measures the probability error in discrete classification tasks in which the
    classes are mutually exclusive (each entry is in exactly one class).  For
    example, each CIFAR-10 image is labeled with one and only one label: an image
    can be a dog or a truck, but not both.
    
    **NOTE:**  While the classes are mutually exclusive, their probabilities
    need not be.  All that is required is that each row of `labels` is
    a valid probability distribution.  If they are not, the computation of the
    gradient will be incorrect.
    
    If using exclusive `labels` (wherein one and only
    one class is true at a time), see `sparse_softmax_cross_entropy_with_logits`.
    
    **WARNING:** This op expects unscaled logits, since it performs a `softmax`
  

In [11]:
help(tf.nn.sparse_softmax_cross_entropy_with_logits)

Help on function sparse_softmax_cross_entropy_with_logits in module tensorflow.python.ops.nn_ops:

sparse_softmax_cross_entropy_with_logits(logits, labels, name=None)
    Computes sparse softmax cross entropy between `logits` and `labels`.
    
    Measures the probability error in discrete classification tasks in which the
    classes are mutually exclusive (each entry is in exactly one class).  For
    example, each CIFAR-10 image is labeled with one and only one label: an image
    can be a dog or a truck, but not both.
    
    **NOTE:**  For this operation, the probability of a given label is considered
    exclusive.  That is, soft classes are not allowed, and the `labels` vector
    must provide a single specific index for the true class for each row of
    `logits` (each minibatch entry).  For soft softmax classification with
    a probability distribution for each entry, see
    `softmax_cross_entropy_with_logits`.
    
    **WARNING:** This op expects unscaled logits, since i

In [16]:
print a.eval()

[[1 2]
 [3 4]]


In [17]:
a.gather(0).eval()

AttributeError: 'Tensor' object has no attribute 'gather'

In [19]:
tf.gather(a, 0).eval()

array([1, 2], dtype=int32)

In [22]:
a[0,:].eval()

array([1, 2], dtype=int32)

In [25]:
b = tf.slice(a, [0, 0], [1,-1])

In [26]:
b.eval()

array([[1, 2]], dtype=int32)

In [27]:
tf.fill([3, 2], b).eval()

ValueError: Shape (1, 2) must have rank 0

In [29]:
tf.concat(0, [b] * 3).eval()

array([[1, 2],
       [1, 2],
       [1, 2]], dtype=int32)

In [30]:
help(tf.pad)

Help on function pad in module tensorflow.python.ops.array_ops:

pad(tensor, paddings, mode='CONSTANT', name=None)
    Pads a tensor.
    
    This operation pads a `tensor` according to the `paddings` you specify.
    `paddings` is an integer tensor with shape `[n, 2]`, where n is the rank of
    `tensor`. For each dimension D of `input`, `paddings[D, 0]` indicates how
    many values to add before the contents of `tensor` in that dimension, and
    `paddings[D, 1]` indicates how many values to add after the contents of
    `tensor` in that dimension. If `mode` is "REFLECT" then both `paddings[D, 0]`
    and `paddings[D, 1]` must be no greater than `tensor.dim_size(D) - 1`. If
    `mode` is "SYMMETRIC" then both `paddings[D, 0]` and `paddings[D, 1]` must be
    no greater than `tensor.dim_size(D)`.
    
    The padded size of each dimension D of the output is:
    
    `paddings[D, 0] + tensor.dim_size(D) + paddings[D, 1]`
    
    For example:
    
    ```python
    # 't' is [[1, 2, 

In [1]:
import tensorflow.nn as nn

ImportError: No module named nn

In [2]:
import tensorflow

In [3]:
tensorflow.nn.absolute_import

_Feature((2, 5, 0, 'alpha', 1), (3, 0, 0, 'alpha', 0), 16384)

In [4]:
import tensorflow.nn as nn

ImportError: No module named nn

In [6]:
import tensorflow.python.ops.nn 

In [7]:
nn = tensorflow.python.ops.nn 

AttributeError: 'module' object has no attribute 'nn'

In [8]:
help(tf.random_uniform)

NameError: name 'tf' is not defined

In [9]:
import tensorflow as tf

In [10]:
help(tf.random_uniform)

Help on function random_uniform in module tensorflow.python.ops.random_ops:

random_uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)
    Outputs random values from a uniform distribution.
    
    The generated values follow a uniform distribution in the range
    `[minval, maxval)`. The lower bound `minval` is included in the range, while
    the upper bound `maxval` is excluded.
    
    For floats, the default range is `[0, 1)`.  For ints, at least `maxval` must
    be specified explicitly.
    
    In the integer case, the random integers are slightly biased unless
    `maxval - minval` is an exact power of two.  The bias is small for values of
    `maxval - minval` significantly smaller than the range of the output (either
    `2**32` or `2**64`).
    
    Args:
      shape: A 1-D integer Tensor or Python array. The shape of the output tensor.
      minval: A 0-D Tensor or Python value of type `dtype`. The lower bound on the
        range of random val

In [11]:
help(tf.random_uniform_initializer)

Help on function random_uniform_initializer in module tensorflow.python.ops.init_ops:

random_uniform_initializer(minval=0.0, maxval=1.0, seed=None, dtype=tf.float32)
    Returns an initializer that generates tensors with a uniform distribution.
    
    Args:
      minval: a python scalar or a scalar tensor. lower bound of the range
        of random values to generate.
      maxval: a python scalar or a scalar tensor. upper bound of the range
        of random values to generate.
      seed: A Python integer. Used to create random seeds. See
        [`set_random_seed`](../../api_docs/python/constant_op.md#set_random_seed)
        for behavior.
      dtype: The data type. Only floating point types are supported.
    
    Returns:
      An initializer that generates tensors with a uniform distribution.
    
    Raises:
      ValueError: if `dtype` is not a floating point type.



In [12]:
help(tf.train.shuffle_batch)

Help on function shuffle_batch in module tensorflow.python.training.input:

shuffle_batch(tensors, batch_size, capacity, min_after_dequeue, num_threads=1, seed=None, enqueue_many=False, shapes=None, allow_smaller_final_batch=False, shared_name=None, name=None)
    Creates batches by randomly shuffling tensors.
    
    This function adds the following to the current `Graph`:
    
    * A shuffling queue into which tensors from `tensors` are enqueued.
    * A `dequeue_many` operation to create batches from the queue.
    * A `QueueRunner` to `QUEUE_RUNNER` collection, to enqueue the tensors
      from `tensors`.
    
    If `enqueue_many` is `False`, `tensors` is assumed to represent a
    single example.  An input tensor with shape `[x, y, z]` will be output
    as a tensor with shape `[batch_size, x, y, z]`.
    
    If `enqueue_many` is `True`, `tensors` is assumed to represent a
    batch of examples, where the first dimension is indexed by example,
    and all members of `tensors` 

In [14]:
help(tf.train.batch)

Help on function batch in module tensorflow.python.training.input:

batch(tensors, batch_size, num_threads=1, capacity=32, enqueue_many=False, shapes=None, dynamic_pad=False, allow_smaller_final_batch=False, shared_name=None, name=None)
    Creates batches of tensors in `tensors`.
    
    The argument `tensors` can be a list or a dictionary of tensors.
    The value returned by the function will be of the same type
    as `tensors`.
    
    This function is implemented using a queue. A `QueueRunner` for the
    queue is added to the current `Graph`'s `QUEUE_RUNNER` collection.
    
    If `enqueue_many` is `False`, `tensors` is assumed to represent a single
    example.  An input tensor with shape `[x, y, z]` will be output as a tensor
    with shape `[batch_size, x, y, z]`.
    
    If `enqueue_many` is `True`, `tensors` is assumed to represent a batch of
    examples, where the first dimension is indexed by example, and all members of
    `tensor_list` should have the same size in 