In [1]:
import tensorflow as tf
sess = tf.InteractiveSession()

In [6]:
x = tf.constant([[1,2,3], [4,8,6]])

In [3]:
y = tf.zeros(x)

ValueError: Shape (2, 3) must have rank 1

In [4]:
help(tf.argmax)

Help on function arg_max in module tensorflow.python.ops.gen_math_ops:

arg_max(input, dimension, name=None)
    Returns the index with the largest value across dimensions of a tensor.
    
    Args:
      input: A `Tensor`. Must be one of the following types: `float32`, `float64`, `int64`, `int32`, `uint8`, `uint16`, `int16`, `int8`, `complex64`, `complex128`, `qint8`, `quint8`, `qint32`, `half`.
      dimension: A `Tensor` of type `int32`.
        int32, 0 <= dimension < rank(input).  Describes which dimension
        of the input Tensor to reduce across. For vectors, use dimension = 0.
      name: A name for the operation (optional).
    
    Returns:
      A `Tensor` of type `int64`.



In [7]:
tf.arg_max(x, 1).eval()

array([2, 1])

In [12]:
tf.reshape(tf.arg_max(x, 1), [tf.shape(x)[0], -1]).eval()

array([[2],
       [1]])

In [13]:
tf.reshape(tf.arg_max(x, 1), [1, -1]).eval()

array([[2, 1]])

In [15]:
tf.zeros([tf.shape(x)[0], tf.shape(x)[1]]).eval()

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]], dtype=float32)

In [16]:
tf.shape(x)[0]

<tf.Tensor 'Squeeze_7:0' shape=() dtype=int32>

In [20]:
tf.zeros([x.get_shape()[0], x.get_shape()[1]]).eval()

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]], dtype=float32)

In [17]:
help(tf.zeros)

Help on function zeros in module tensorflow.python.ops.array_ops:

zeros(shape, dtype=tf.float32, name=None)
    Creates a tensor with all elements set to zero.
    
    This operation returns a tensor of type `dtype` with shape `shape` and
    all elements set to zero.
    
    For example:
    
    ```python
    tf.zeros([3, 4], int32) ==> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
    ```
    
    Args:
      shape: Either a list of integers, or a 1-D `Tensor` of type `int32`.
      dtype: The type of an element in the resulting `Tensor`.
      name: A name for the operation (optional).
    
    Returns:
      A `Tensor` with all elements set to zero.



In [1]:
import tensorflow as tf

In [2]:
tf.get_variable

<function tensorflow.python.ops.variable_scope.get_variable>

In [3]:
help(tf.get_variable)

Help on function get_variable in module tensorflow.python.ops.variable_scope:

get_variable(name, shape=None, dtype=tf.float32, initializer=None, regularizer=None, trainable=True, collections=None, caching_device=None, partitioner=None, validate_shape=True, custom_getter=None)
    Gets an existing variable with these parameters or create a new one.
    
    This function prefixes the name with the current variable scope
    and performs reuse checks. See the
    [Variable Scope How To](../../how_tos/variable_scope/index.md)
    for an extensive description of how reusing works. Here is a basic example:
    
    ```python
    with tf.variable_scope("foo"):
        v = tf.get_variable("v", [1])  # v.name == "foo/v:0"
        w = tf.get_variable("w", [1])  # w.name == "foo/w:0"
    with tf.variable_scope("foo", reuse=True)
        v1 = tf.get_variable("v")  # The same as v above.
    ```
    
    If initializer is `None` (the default), the default initializer passed in
    the variable sc

In [4]:
help(tf.random_normal_initializer)

Help on function random_normal_initializer in module tensorflow.python.ops.init_ops:

random_normal_initializer(mean=0.0, stddev=1.0, seed=None, dtype=tf.float32)
    Returns an initializer that generates tensors with a normal distribution.
    
    Args:
      mean: a python scalar or a scalar tensor. Mean of the random values
        to generate.
      stddev: a python scalar or a scalar tensor. Standard deviation of the
        random values to generate.
      seed: A Python integer. Used to create random seeds. See
        [`set_random_seed`](../../api_docs/python/constant_op.md#set_random_seed)
        for behavior.
      dtype: The data type. Only floating point types are supported.
    
    Returns:
      An initializer that generates tensors with a normal distribution.
    
    Raises:
      ValueError: if `dtype` is not a floating point type.



In [5]:
help(tf.random_normal)

Help on function random_normal in module tensorflow.python.ops.random_ops:

random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)
    Outputs random values from a normal distribution.
    
    Args:
      shape: A 1-D integer Tensor or Python array. The shape of the output tensor.
      mean: A 0-D Tensor or Python value of type `dtype`. The mean of the normal
        distribution.
      stddev: A 0-D Tensor or Python value of type `dtype`. The standard deviation
        of the normal distribution.
      dtype: The type of the output.
      seed: A Python integer. Used to create a random seed for the distribution.
        See
        [`set_random_seed`](../../api_docs/python/constant_op.md#set_random_seed)
        for behavior.
      name: A name for the operation (optional).
    
    Returns:
      A tensor of the specified shape filled with random normal values.



In [6]:
import tf.nn

ImportError: No module named tf.nn

In [7]:
from tensorflow.python.ops import nn

In [8]:
from tf.python.ops import nn

ImportError: No module named tf.python.ops