In [1]:
import tensorflow as tf
import numpy as np

# Create input data
X = np.random.randn(2, 10, 8)
 
# The second example is of length 6 
X[1,6:] = 0
X_lengths = [10, 6]

print(X)
 
cell = tf.nn.rnn_cell.LSTMCell(num_units=64, state_is_tuple=True)
 
outputs, last_states = tf.nn.dynamic_rnn(
    cell=cell,
    dtype=tf.float64,
    sequence_length=X_lengths,
    inputs=X)
 
result = tf.contrib.learn.run_n(
    {"outputs": outputs, "last_states": last_states},
    n=1,
    feed_dict=None)
 
assert result[0]["outputs"].shape == (2, 10, 64)
 
# Outputs for the second example past past length 6 should be 0
assert (result[0]["outputs"][1,7,:] == np.zeros(cell.output_size)).all()

print(result[0]["outputs"])

[[[ 0.28794634  2.24618216 -1.97283004  0.92066471 -0.73093551 -0.64945863
   -0.18471969  0.58196102]
  [ 0.07544773 -0.20987041 -0.21630577  1.19565045 -1.3157568  -0.80290086
    0.20042541 -0.01066429]
  [ 0.43314344  1.06517464 -0.58431914 -0.29946403  0.44902691  1.48603589
    0.64400584  0.67323295]
  [-1.41948713  1.56461955 -0.82785776 -0.10918209 -0.13141574 -0.72945009
   -0.124771   -0.73066026]
  [ 0.09971319  1.06243739  0.48804969  0.99623139 -1.10989328  1.66691397
   -0.45954553 -0.55229322]
  [-0.84868919  0.9099634   0.39544008 -0.66858366  0.37115451  1.81550062
   -0.66132761  0.20715826]
  [-0.40118779  0.82397573  2.46331036 -0.52294061 -0.52626233  0.59400978
   -0.10750573 -1.52702152]
  [ 1.05073328  0.36547852  0.31155161 -0.90147782 -1.95760908 -0.19899968
    1.27541288  0.30011154]
  [ 1.514751    0.02449048  0.50444853 -1.39265863 -0.19389469  0.39399868
   -0.59733017 -1.39454893]
  [ 0.19980941 -0.35414549 -2.01738314  0.91011222  0.36350244 -1.3109528

In [6]:
tf.nn.dynamic_rnn?

In [3]:
X = np.random.randn(2, 10, 8)
 
X[1,6,:] = 0
X_lengths = [10, 6]
 
cell = tf.nn.rnn_cell.LSTMCell(num_units=64, state_is_tuple=True)
 
outputs, states  = tf.nn.bidirectional_dynamic_rnn(
    cell_fw=cell,
    cell_bw=cell,
    dtype=tf.float64,
    sequence_length=X_lengths,
    inputs=X)
 
output_fw, output_bw = outputs
states_fw, states_bw = states

In [4]:
tf.sign?

In [5]:
tf.reduce_max?

In [7]:
tf.nn.sampled_softmax_loss?

In [12]:
tf.split?

In [9]:
tf.nn.rnn?

In [10]:
tf.nn.dynamic_rnn?

In [11]:
tf.expand_dims?

In [17]:
x = tf.constant([[1,2,3,4],
                 [4,5,6,7],
                 [7,8,9,10]])
sess = tf.InteractiveSession()
print x.eval()

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


Exception AssertionError: AssertionError("Nesting violated for default stack of <type 'weakref'> objects",) in <bound method InteractiveSession.__del__ of <tensorflow.python.client.session.InteractiveSession object at 0x23b1290>> ignored


In [18]:
batch_size = 3
num_steps = 4
y = tf.reshape(x,[-1])
print y.eval()

[ 1  2  3  4  4  5  6  7  7  8  9 10]


In [20]:
z = tf.split(0, num_steps, y)
for item in z:
    print item.eval()

[1 2 3]
[4 4 5]
[6 7 7]
[ 8  9 10]


In [21]:
u = tf.reshape(y, [batch_size, num_steps])
print u.eval()

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [24]:
z = tf.split(1, num_steps, u)
for item in z:
    item = tf.squeeze(item, [1])
    print item.eval()

[1 4 7]
[2 5 8]
[3 6 9]
[ 4  7 10]


In [25]:
tf.reduce_mean?

In [26]:
z[0].eval()

array([[1],
       [4],
       [7]], dtype=int32)

In [28]:
(tf.reduce_sum(z[0]) / tf.reduce_sum(tf.sign(z[0]))).eval()

4

In [35]:
x = tf.constant([1., 0., 3., 4.])

In [36]:
(tf.reduce_sum(x) / tf.reduce_sum(tf.sign(x))).eval()

2.6666667

In [31]:
(tf.reduce_sum(x) / tf.reduce_sum(tf.cast(tf.sign(x), tf.float32))).eval()

ValueError: Tensor conversion requested dtype int32 for Tensor with dtype float32: 'Tensor("Sum_7:0", shape=(), dtype=float32)'

In [37]:
tf.reduce_mean??